/**
 * author       Mat Hopwood
 * copyright    2014 Mat Hopwood
 * More info    http://www.gojieditor.com
 */
function Actor(){this.actors=[];this.removals=[];this.joints=[];this.iscanvas=!1;this.frame_count=0;this.tag=this.name="";this.id=-1;this.parent=this.scene=null;this.visible=this.active=!0;this.touchable=!1;this.h=this.w=this.y=this.x=this.layer=0;this.oy=this.ox=.5;this.absolute_origin=!1;this.rotation=0;this.accum_scale_y=this.accum_scale_x=this.scale_y=this.scale_x=1;this.depth=0;this.accum_opacity=this.opacity=1;this.use_parent_opacity=!0;this.frame_speed=this.current_frame=0;this.atlas=this.bitmap=
null;this.vd=this.vy=this.vx=this.vr=0;this.vd_damping=this.vy_damping=this.vx_damping=this.vr_damping=1;this.body=null;this.transform=[];this.transform_dirty=this.use_transform=!0;this.wrap_position=this.ignore_camera=!1;this.dock_y=this.dock_x=0;this.margin=[0,0,0,0];this.clip_children=this.bubbling=!1;this.clip_margin=[0,0,0,0];this.touchmove=this.touching=!1}Object.defineProperty(Actor.prototype,"_x",{get:function(){return this.x},set:function(a){this.x=a;this.transform_dirty=!0}});
Object.defineProperty(Actor.prototype,"_y",{get:function(){return this.y},set:function(a){this.y=a;this.transform_dirty=!0}});Object.defineProperty(Actor.prototype,"_ox",{get:function(){return this.ox},set:function(a){this.ox=a;this.transform_dirty=!0}});Object.defineProperty(Actor.prototype,"_oy",{get:function(){return this.oy},set:function(a){this.oy=a;this.transform_dirty=!0}});
Object.defineProperty(Actor.prototype,"_rotation",{get:function(){return this.rotation},set:function(a){this.rotation=a;this.transform_dirty=!0}});Object.defineProperty(Actor.prototype,"_scale_x",{get:function(){return this.scale_x},set:function(a){this.scale_x=a;this.transform_dirty=!0}});Object.defineProperty(Actor.prototype,"_scale_y",{get:function(){return this.scale_y},set:function(a){this.scale_y=a;this.transform_dirty=!0}});
Object.defineProperty(Actor.prototype,"_depth",{get:function(){return this.depth},set:function(a){this.depth=a;this.transform_dirty=!0}});Actor.prototype.setPosition=function(a,b){this.x=a;this.y=b;this.transform_dirty=!0};Actor.prototype.setOrigin=function(a,b){this.ox=a;this.oy=b;this.transform_dirty=!0};Actor.prototype.setScale=function(a,b){this.scale_x=a;this.scale_y=b;this.transform_dirty=!0};Actor.prototype.setRotation=function(a){this.rotation=a;this.transform_dirty=!0};
Actor.prototype.setDepth=function(a){this.depth=a;this.transform_dirty=!0};Actor.prototype.release=function(){if(void 0!=this.onDestroy)this.onDestroy();this.releaseJoints();this.releaseBody()};Actor.prototype.destroy=function(){null!=this.parent?this.parent.removeActor(this):null!=this.scene&&this.scene.removeActor(this)};Actor.prototype.addActor=function(a){this.actors.push(a);a.parent=this;a.scene=this.scene};Actor.prototype.removeActor=function(a){this.removals.push(a)};
Actor.prototype.removeActorsWithTag=function(a){for(var b=this.actors,c=b.length,d=this.removals,e=0;e<c;e++)b[e].tag==a&&d.push(b[e])};Actor.prototype.cleanupDestroyedActors=function(){var a=this.removals.length;if(0<a)for(var b=this.removals,c=this.actors,d=c.length,e=0;e<a;e++)for(var f=b[e],g=0;g<d;g++)if(f==c[g]){f.release();c.splice(g,1);d--;break}this.removals=[]};Actor.prototype.findActor=function(a){for(var b=this.actors,c=b.length,d=0;d<c;d++)if(b[d].name==a)return b[d];return null};
Actor.prototype.findActorDeep=function(a){for(var b=this.actors,c=b.length,d=0;d<c;d++){if(b[d].name==a)return b[d];var e=b[d].findActorDeep(a);if(null!=e)return e}return null};Actor.prototype.destroy=function(){null!=this.parent?this.parent.removeActor(this):this.scene.removeActor(this)};Actor.prototype.bringToFront=function(a){this.removeActor(a);this.addActor(a)};
Actor.prototype.onBeginTouchBase=function(a){this.touching=!0;if(this.bubbling&&null!=this.parent)this.parent.onBeginTouchBase(a);if(void 0!=this.onBeginTouch)this.onBeginTouch(a)};Actor.prototype.onEndTouchBase=function(a){if(this.touching&&void 0!=this.onTapped)this.onTapped(a);this.touchmove=this.touching=!1;if(this.bubbling&&null!=this.parent)this.parent.onEndTouchBase(a);if(void 0!=this.onEndTouch)this.onEndTouch(a)};
Actor.prototype.onMoveTouchBase=function(a){this.touchmove=!0;if(this.bubbling&&null!=this.parent)this.parent.onMoveTouchBase(a);if(void 0!=this.onMoveTouch)this.onMoveTouch(a)};Actor.prototype.releaseBody=function(){null!=this.body&&(this.scene.world.DestroyBody(this.body),this.body=null)};Actor.prototype.releaseJoints=function(){if(null!=this.body){for(var a=0;a<this.joints.length;a++)this.scene.world.DestroyJoint(this.joints[a]);this.joints=null}};
Actor.prototype.initBody=function(a,b,c){var d=this.scene;this.use_transform=!0;var e=new Box2D.Dynamics.b2BodyDef,f=d.world_scale;e.type="static"==a?Box2D.Dynamics.b2Body.b2_staticBody:"kinematic"==a?Box2D.Dynamics.b2Body.b2_kinematicBody:Box2D.Dynamics.b2Body.b2_dynamicBody;e.position.Set(this.x/f,this.y/f);e.angle=this.rotation;e.fixedRotation=b;e.bullet=c;this.body=d.world.CreateBody(e);this.body.SetUserData(this)};
Actor.prototype.addFixture=function(a){var b;if(a.type==Shape.TypeBox){b=new Box2D.Dynamics.b2FixtureDef;var c=this.scene.world_scale;b.shape=new Box2D.Collision.Shapes.b2PolygonShape;b.shape.SetAsBox(a.width/(2*c),a.height/(2*c))}else if(a.type==Shape.TypeCircle)b=new Box2D.Dynamics.b2FixtureDef,c=this.scene.world_scale,b.shape=new Box2D.Collision.Shapes.b2CircleShape(a.radius/c);else if(a.type==Shape.TypePolygon){b=new Box2D.Dynamics.b2FixtureDef;c=this.scene.world_scale;b.shape=new Box2D.Collision.Shapes.b2PolygonShape;
for(var d=a.points,e=[],f=d.length,g=0;g<f;g+=2)e.push({x:d[g]/c,y:d[g+1]/c});b.shape.SetAsArray(e,e.length)}void 0!=a.density&&(b.density=a.density);void 0!=a.friction&&(b.friction=a.friction);void 0!=a.restitution&&(b.restitution=a.restitution);void 0!=a.is_sensor&&(b.isSensor=a.is_sensor);this.body.CreateFixture(b)};
Actor.prototype.addJoint=function(a){var b,c=this.scene,d=c.world,c=c.world_scale,e=Box2D.Common.Math.b2Vec2,f=this.body,g=a.actor_b.body,h=f.GetWorldCenter(),l=g.GetWorldCenter(),k=new e(h.x,h.y);k.x+=a.anchor_a.x/c;k.y+=a.anchor_a.y/c;var m=new e(l.x,l.y);m.x+=a.anchor_b.x/c;m.y+=a.anchor_b.y/c;"weld"==a.type?(b=new Box2D.Dynamics.Joints.b2WeldJointDef,b.Initialize(f,g,k),b.collideConnected=a.self_collide):"distance"==a.type?(b=new Box2D.Dynamics.Joints.b2DistanceJointDef,b.Initialize(f,g,k,m),
b.collideConnected=a.self_collide,b.frequencyHz=a.frequency,b.dampingRatio=a.damping):"revolute"==a.type?(b=new Box2D.Dynamics.Joints.b2RevoluteJointDef,b.Initialize(f,g,k),b.collideConnected=a.self_collide,a.limit_joint&&(b.enableLimit=!0,b.lowerAngle=Math.PI/180*a.lower_limit,b.upperAngle=Math.PI/180*a.upper_limit),a.motor_enabled&&(b.enableMotor=!0,b.motorSpeed=a.motor_speed,b.maxMotorTorque=a.max_motor_torque)):"prismatic"==a.type?(b=new Box2D.Dynamics.Joints.b2PrismaticJointDef,b.Initialize(f,
g,k,new e(a.axis.x,a.axis.y)),b.collideConnected=a.self_collide,a.limit_joint&&(b.enableLimit=!0,b.lowerTranslation=a.lower_limit/c,b.upperTranslation=a.upper_limit/c),a.motor_enabled&&(b.enableMotor=!0,b.motorSpeed=a.motor_speed,b.maxMotorForce=a.max_motor_force)):"pulley"==a.type?(h=new e(h.x,h.y),h.x+=a.ground_a.x/c,h.y+=a.ground_a.y/c,e=new e(l.x,l.y),e.x+=a.ground_b.x/c,e.y+=a.ground_b.y/c,b=new Box2D.Dynamics.Joints.b2PulleyJointDef,b.Initialize(f,g,h,e,k,m,a.ratio),b.collideConnected=a.self_collide):
"wheel"==a.type&&(b=new Box2D.Dynamics.Joints.b2LineJointDef,b.Initialize(f,g,k,a.axis),b.collideConnected=a.self_collide,a.limit_joint&&(b.enableLimit=!0,b.lowerTranslation=a.lower_limit/c,b.upperTranslation=a.upper_limit/c),a.motor_enabled&&(b.enableMotor=!0,b.motorSpeed=a.motor_speed,b.maxMotorForce=a.max_motor_force));this.joints.push(d.CreateJoint(b))};Actor.prototype.removeJoint=function(a){for(var b=this.joints,c=b.length,d=0;d<c;d++)if(b[d]==a){world.DestroyJoint(a);b.splice(d,1);break}};
Actor.prototype.updateTransform=function(){var a=this.transform;if(this.transform_dirty){null==this.parent?(this.accum_scale_x=this.scale_x,this.accum_scale_y=this.scale_y):(this.accum_scale_x=this.scale_x*this.parent.scale_x,this.accum_scale_y=this.scale_y*this.parent.scale_y);var b=this.scene,c=this.rotation,d=this.scale_x,e=this.scale_y,f=Math.cos(c),c=Math.sin(c);if(0!=this.depth){var g=1/this.depth,d=d*g,e=e*g;a[4]=(this.x-b.camera_x)*g;a[5]=(this.y-b.camera_y)*g}else a[4]=this.x,a[5]=this.y;
a[0]=f*d;a[1]=c*d;a[2]=-c*e;a[3]=f*e;this.transform_dirty=!1}if(null!=this.parent){var g=this.parent.transform,b=g[0],d=g[1],e=g[2],f=g[3],c=g[4],g=g[5],h=a[0],l=a[1],k=a[2],m=a[3],n=a[4],p=a[5];a[0]=b*h+e*l;a[1]=d*h+f*l;a[2]=b*k+e*m;a[3]=d*k+f*m;a[4]=b*n+e*p+c;a[5]=d*n+f*p+g}};
Actor.prototype.draw=function(){if(this.visible){var a=this.scene,b=a.app.display,c=b.context,d=null;null!=this.atlas&&(d=this.atlas.getFrame(this.current_frame));var e=b.canvas_width/2+this.scene.x,b=b.canvas_height/2+this.scene.y;this.accum_opacity=null!=this.parent&&this.use_parent_opacity?this.parent.accum_opacity*this.opacity:this.opacity*this.scene.opacity;c.globalAlpha=this.accum_opacity;if(this.use_transform){var f=this.ox,g=this.oy;this.absolute_origin||(f*=this.w,g*=this.h);f=f+.5<<0;g=
g+.5<<0;this.ignore_camera||0!=this.depth||(e-=a.camera_x,b-=a.camera_y);this.updateTransform();a=this.transform;c.setTransform(a[0],a[1],a[2],a[3],a[4]+e,a[5]+b);null!=this.atlas?c.drawImage(this.atlas.bitmap.image,d.x,d.y,d.w,d.h,-f,-g,this.w,this.h):null!=this.bitmap&&c.drawImage(this.bitmap.image,-f,-g,this.w,this.h);this.clip_children&&(c.save(),c.beginPath(),c.setTransform(a[0],a[1],a[2],a[3],a[4]+e,a[5]+b),d=this.clip_margin,c.rect(-f+d[0],-g+d[1],this.w-d[2]-d[0],this.h-d[3]-d[1]),c.clip())}else f=
this.x,g=this.y,null!=this.parent&&(f+=this.parent.x,g+=this.parent.y),this.ignore_camera||(f-=a.camera_x,g-=a.camera_y),f=f+e+.5<<0,g=g+b+.5<<0,c.setTransform(1,0,0,1,0,0),null!=this.atlas?c.drawImage(this.atlas.bitmap.image,d.x,d.y,d.w,d.h,f,g,this.w,this.h):null!=this.bitmap&&c.drawImage(this.bitmap.image,f,g,this.w,this.h),this.clip_children&&(c.save(),c.beginPath(),d=this.clip_margin,c.rect(f+d[0],g+d[1],this.w-d[2]-d[0],this.h-d[3]-d[1]),c.clip());d=this.actors.length;if(0<d)for(e=this.actors,
a=0;a<d;a++)e[a].draw();this.clip_children&&c.restore()}};
Actor.prototype.baseUpdate=function(a){if(!this.active)return!1;if(void 0!=this.onTick)this.onTick(a);var b=this.scene.app.display;if(null!=this.atlas){this.current_frame+=this.frame_speed*a;var c=this.atlas.getMaxFrames();this.current_frame>c&&(this.current_frame-=c)}if(null!=this.body){var c=this.body.GetPosition(),d=this.scene.world_scale;this.setRotation(this.body.GetAngle());this.setPosition(c.x*d,c.y*d)}else this.rotation+=this.vr*a,this.vr*=this.vr_damping,this.x+=this.vx*a,this.vx*=this.vx_damping,
this.y+=this.vy*a,this.vy*=this.vy_damping,this.transform_dirty=!0;0!=this.vd&&(this.depth+=this.vd*a,this.vd*=this.vd_damping);if(this.wrap_position){var e=this.scene,c=e.extents[0],d=c+e.extents[2],f=e.extents[1],e=f+e.extents[3];this.x<c?this.x=d:this.x>d&&(this.x=c);this.y<f?this.y=e:this.y>e&&(this.y=f)}null!=this.parent&&this.parent.iscanvas||(0!=this.dock_x&&(1==this.dock_x?this.x=-b.canvas_width/2+this.w/2+this.margin[0]:2==this.dock_x&&(this.x=b.canvas_width/2-this.w/2-this.margin[1])),0!=
this.dock_y&&(1==this.dock_y?this.y=-b.canvas_height/2+this.h/2+this.margin[2]:2==this.dock_y&&(this.y=b.canvas_height/2-this.h/2-this.margin[3])));b=this.actors.length;if(0<b)for(c=this.actors,d=0;d<b;d++)c[d].update(a);this.cleanupDestroyedActors();this.frame_count++};Actor.prototype.update=function(a){return this.baseUpdate(a)};Actor.prototype.updateToPhysics=function(a){this.body.SetLinearVelocity(new Box2D.Common.Math.b2Vec2(this.vx,this.vy));this.body.SetAbgularVelocity(this.vr)};
Actor.prototype.hitTest=function(a){if(!this.touchable)return null;var b=this.actors.length,c;if(0<b)for(var d=this.actors,e=0;e<b;e++)if(c=d[e].hitTest(a),null!=c)return c;b=this.scene;if(this.use_transform){c=this.transform;var f=c[4]+b.x,d=c[5]+b.y;this.ignore_camera||(f-=b.camera_x,d-=b.camera_y);e=this.accum_scale_x;b=this.accum_scale_y;f=(a.x-f)/e;d=(a.y-d)/b;a=f*c[0]+d*c[1];d=f*c[2]+d*c[3];c=this.w*e/2;b=this.h*b/2;if(a>=-c&&a<=c&&d>=-b&&d<=b)return this}else if(f=this.x+b.x,d=this.y+b.y,this.ignore_camera||
(f-=b.camera_x,d-=b.camera_y),f=a.x-f,d=a.y-d,c=this.w,b=this.h,0<=f&&f<=c&&0<=d&&d<=b)return this;return null};function Ease(){}Ease.linear=0;Ease.quadin=1;Ease.quadout=2;Ease.cubicin=3;Ease.cubicout=4;Ease.quartin=5;Ease.quartout=6;Ease.sin=7;Ease.easingFuncs=[function(a){return a},function(a){return a*a},function(a){return a*(2-a)},function(a){return a*a*a},function(a){a-=1;return a*a*a+1},function(a){return a*a*a*a},function(a){a-=1;return-(a*a*a*a-1)},function(a){return Math.sin(a*Math.PI/2)}];
function Animation(a,b,c,d,e,f,g){this.timeline=a;this.state=Animation.AS_playing;this.time=-1E-6;this.repeats_left=f;this.index=-1;this.target=b;this.property=c;this.frames=d;this.times=e;this.easing=g;this.repeat=f;this.destroy=!0;this.actions=[];this.time_scale=1}Animation.AS_playing=0;Animation.AS_paused=1;Animation.prototype.pause=function(){this.state=Animation.AS_paused};Animation.prototype.play=function(){this.state=Animation.AS_playing};
Animation.prototype.restart=function(){this.state=Animation.AS_playing;this.time=-1E-6;this.index=-1;this.repeats_left=this.repeat};
Animation.prototype.update=function(a){if(this.state==Animation.AS_playing){a*=this.time_scale;a=this.time+a;for(var b=this.times,c=this.frames,d=this.times.length,e=this.index,f=e;f<d;f++){var g=b[f];if(a<g){this.index=f;if(a>=b[0]){this.index!=e&&(d=this.actions[this.index-1],void 0!=d&&d());var e=b[f-1],d=c[f-1],g=g-e,h=c[f]-d,e=a-e;0!=e&&(this.target[this.property]=void 0!=this.easing?d+h*Ease.easingFuncs[this.easing[f-1]](e/g):d+h*e/g)}break}}f=b[b.length-1];if(a>f){0<this.repeat&&this.repeats_left--;
if(0==this.repeat||0<this.repeats_left){a-=f;if(void 0!=this.onRepeat)this.onRepeat(this);this.target[this.property]=c[0]}else{this.target[this.property]=c[b.length-1];this.state=Animation.AS_paused;if(void 0!=this.onEnd)this.onEnd(this);this.destroy&&this.timeline.remove(this)}this.index=-1}this.time=a}};Animation.prototype.setTime=function(a){this.time=a;this.index=-1;this.update(0)};Animation.prototype.setAction=function(a,b){this.actions[a]=b};
function Timeline(a,b,c,d,e,f){this.anims=[];this.manager=null;this.name="";void 0!=a&&this.add(a,b,c,d,e,f)}Timeline.prototype.add=function(a,b,c,d,e,f){a=new Animation(this,a,b,c,d,e,f);this.anims.push(a);return a};Timeline.prototype.remove=function(a){for(var b=this.anims,c=b.length,d=0;d<c;d++)if(b[d]==a){b.splice(d,1);break}};Timeline.prototype.find=function(a){for(var b=this.timelines,c=b.length,d=0;d<c;d++)if(b[d].name==a)return b[d];return null};
Timeline.prototype.pause=function(){for(var a=this.anims.length,b=0;b<a;b++)this.anims[b].pause()};Timeline.prototype.play=function(){for(var a=this.anims.length,b=0;b<a;b++)this.anims[b].play()};Timeline.prototype.restart=function(){for(var a=this.anims.length,b=0;b<a;b++)this.anims[b].restart()};Timeline.prototype.print=function(){for(var a=this.anims.length,b=0;b<a;b++)console.log(this.anims[b])};
Timeline.prototype.update=function(a){var b=this.anims.length;if(0==b&&void 0!=this.manager)this.manager.remove(this);else for(b-=1;0<=b;b--)this.anims[b].update(a)};function TimelineManager(){this.timelines=[]}TimelineManager.prototype.add=function(a){this.timelines.push(a);a.manager=this};TimelineManager.prototype.remove=function(a){for(var b=this.timelines,c=b.length,d=0;d<c;d++)if(b[d]==a){b.splice(d,1);break}};TimelineManager.prototype.pause=function(){for(var a=this.timelines.length,b=0;b<a;b++)this.timelines[b].pause()};
TimelineManager.prototype.play=function(){for(var a=this.timelines.length,b=0;b<a;b++)this.timelines[b].play()};TimelineManager.prototype.restart=function(){for(var a=this.timelines.length,b=0;b<a;b++)this.timelines[b].restart()};TimelineManager.prototype.print=function(){for(var a=this.timelines.length,b=0;b<a;b++)console.log(this.timelines[b])};TimelineManager.prototype.update=function(a){for(var b=this.timelines.length-1;0<=b;b--)this.timelines[b].update(a)};function TheApp(a){this.touched=!1;this.touch_pos={x:0,y:0};this.touch_drag_y=this.touch_drag_x=0;this.scenes=[];this.removals=[];this.canvas=a;this.touch_supported=!1;this.allow_touchables=!0;this.target_frame_rate=60;this.focus_scene=null;this.clear_canvas=!1;this.touch_focus=null;this.debug=!1;this.timer=null;this.timelines=new TimelineManager;this.bitmaps=[];this.brushes=[];this.shapes=[];this.materials=[];this.geoms=[];this.sounds=[];this.display=new Display(this.canvas);this.touch_supported?
(a.addEventListener("touchstart",this.onTouchStart,!1),a.addEventListener("touchmove",this.onTouchMove,!1),a.addEventListener("touchend",this.onTouchEnd,!1)):(a.addEventListener("mousedown",this.onTouchStart,!1),a.addEventListener("mousemove",this.onTouchMove,!1),a.addEventListener("mouseup",this.onTouchEnd,!1),a.addEventListener("mouseout",this.onTouchEnd,!1))}TheApp.version=1.2;
TheApp.prototype.onTouchStart=function(a){var b=window.app;b.touch_supported&&(a.stopPropagation(),a.preventDefault());var c=b.display;b.touched=!0;b.touch_pos=b.touch_supported?c.getCanvasPoint(a.touches[0].pageX,a.touches[0].pageY):c.getCanvasPoint(a.pageX,a.pageY);b.touch_pos.x-=c.canvas_width/2;b.touch_pos.y-=c.canvas_height/2;if(null!=b.focus_scene)b.focus_scene.onBeginTouchBase(b.touch_pos);b.allow_touchables&&(a=b.findHitActor(b.touch_pos),null!=a&&(b.touch_focus=a,a.onBeginTouchBase(b.touch_pos)))};
TheApp.prototype.onTouchEnd=function(a){var b=window.app;b.touch_supported&&(a.stopPropagation(),a.preventDefault());var c=b.display;b.touched=!1;b.touch_pos=b.touch_supported?c.getCanvasPoint(a.touches[0].pageX,a.touches[0].pageY):c.getCanvasPoint(a.pageX,a.pageY);b.touch_pos.x-=c.canvas_width/2;b.touch_pos.y-=c.canvas_height/2;if(null!=b.focus_scene)b.focus_scene.onEndTouchBase(b.touch_pos);if(b.allow_touchables){a=b.findHitActor(b.touch_pos);if(null!=a)a.onEndTouchBase(b.touch_pos);if(null!=b.touch_focus){if(void 0!=
b.touch_focus.onLostTouchFocus)b.touch_focus.onLostTouchFocus(b.touch_pos);b.touch_focus=null}}};
TheApp.prototype.onTouchMove=function(a){var b=window.app;b.touch_supported&&(a.stopPropagation(),a.preventDefault());var c=b.touch_pos.x,d=b.touch_pos.y,e=b.display;b.touch_pos=b.touch_supported?e.getCanvasPoint(a.touches[0].pageX,a.touches[0].pageY):e.getCanvasPoint(a.pageX,a.pageY);b.touch_pos.x-=e.canvas_width/2;b.touch_pos.y-=e.canvas_height/2;b.touch_drag_x=c-b.touch_pos.x;b.touch_drag_y=d-b.touch_pos.y;if(null!=b.focus_scene)b.focus_scene.onMoveTouchBase(b.touch_pos);if(b.allow_touchables&&
(a=b.findHitActor(b.touch_pos),null!=a))a.onMoveTouchBase(b.touch_pos)};TheApp.prototype.addScene=function(a){this.scenes.push(a);a.app=this};TheApp.prototype.removeScene=function(a,b){this.removals.push(a)};TheApp.prototype.cleanupDestroyedScenes=function(){var a=this.removals.length;if(0<a)for(var b=this.removals,c=this.scenes,d=c.length,e=0;e<a;e++)for(var f=b[e],g=0;g<d;g++)if(f==c[e]){f.release();c.splice(g,1);d--;break}this.removals=[]};
TheApp.prototype.findScene=function(a){for(var b=this.scemes,c=b.length,d=0;d<c;d++)if(b[d].name==a)return b[d];return null};TheApp.prototype.addResource=function(a,b){var c;if("brush"==b)c=this.brushes;else if("sound"==b)c=this.sounds;else if("shape"==b)c=this.shapes;else if("material"==b)c=this.materials;else if("bitmap"==b)c=this.bitmaps;else if("geometry"==b)c=this.geoms;else return;c.push(a)};
TheApp.prototype.findResource=function(a,b){var c;if("brush"==b)c=this.brushes;else if("sound"==b)c=this.sounds;else if("shape"==b)c=this.shapes;else if("material"==b)c=this.materials;else if("bitmap"==b)c=this.bitmaps;else if("geometry"==b)c=this.geoms;else return null;for(var d=c.length,e=0;e<d;e++)if(c[e].name==a)return c[e];console.log("resource '"+a+"' ("+b+") not found");return null};TheApp.prototype.draw=function(){for(var a=this.scenes,b=a.length,c=0;c<b;c++)a[c].draw()};
TheApp.prototype.update=function(a){var b=this.scenes,c=b.length;window.app.timelines.update(a);for(var d=0;d<c;d++)b[d].update(a);this.cleanupDestroyedScenes()};TheApp.prototype.mainLoop=function(){app.clear_canvas&&app.display.clear(!0);app.update(1/app.target_frame_rate);app.draw()};TheApp.prototype.start=function(){this.timer=setInterval(this.mainLoop,1E3/this.target_frame_rate)};TheApp.prototype.findHitActor=function(a){return null!=this.focus_scene?this.focus_scene.findHitActor(a):null};ArcActor.prototype=new Actor;ArcActor.prototype.constructor=ArcActor;ArcActor.prototype.parent=Actor.prototype;function ArcActor(){this.stroke_style=this.fill_style="";this.radius=1;this.start_angle=0;this.end_angle=2*Math.PI;this.filled=!0;Actor.call(this);this.oy=this.ox=0}ArcActor.prototype.update=function(a){return this.baseUpdate(a)};
ArcActor.prototype.draw=function(){if(this.visible){var a=this.scene,b=app.display,c=b.context;this.filled&&""!=this.fill_style&&(c.fillStyle=this.fill_style);this.filled||""==this.stroke_style||(c.strokeStyle=this.stroke_style);var d=b.canvas_width/2+a.x,e=b.canvas_height/2+a.y;this.accum_opacity=null!=this.parent&&this.use_parent_opacity?this.parent.accum_opacity*this.opacity:this.opacity*this.scene.opacity;c.globalAlpha=this.accum_opacity;if(this.use_transform){var f=this.ox,g=this.oy;this.absolute_origin||
(f*=this.w,g*=this.h);f=f+.5<<0;g=g+.5<<0;this.ignore_camera||0!=this.depth||(d-=a.camera_x,e-=a.camera_y);this.updateTransform();a=this.transform;c.setTransform(a[0],a[1],a[2],a[3],a[4]+d,a[5]+e);b.drawArc(-f,-g,this.radius,this.start_angle,this.end_angle,this.filled);this.clip_children&&(c.save(),c.beginPath(),c.setTransform(a[0],a[1],a[2],a[3],a[4]+d,a[5]+e),c.arc(-f,-g,this.radius,0,2*Math.PI,!1),c.clip())}else f=this.x,g=this.y,null!=this.parent&&(f+=this.parent.x,g+=this.parent.y),this.ignore_camera||
(f-=a.camera_x,g-=a.camera_y),f=f+d+.5<<0,g=g+e+.5<<0,c.setTransform(1,0,0,1,0,0),b.drawArc(f,g,this.radius,this.start_angle,this.end_angle,this.filled),this.clip_children&&(c.save(),c.beginPath(),c.arc(f,g,this.radius,0,2*Math.PI,!1),c.clip());b=this.actors.length;if(0<b)for(d=this.actors,e=0;e<b;e++)d[e].draw();this.clip_children&&c.restore()}};
ArcActor.prototype.hitTest=function(a){if(!this.touchable)return null;var b=this.actors.length,c;if(0<b)for(var d=this.actors,e=0;e<b;e++)if(c=d[e].hitTest(a),null!=c)return c;c=this.scene;this.use_transform?(b=this.transform,e=b[4]+c.x,d=b[5]+c.y,this.ignore_camera||(e-=c.camera_x,d-=c.camera_y),c=this.accum_scale_x,e=(a.x-e)/c,d=(a.y-d)/this.accum_scale_y,a=e*b[0]+d*b[1],d=e*b[2]+d*b[3],b=this.radius*c,b*=b,a=a*a+d*d):(e=this.x+c.x,d=this.y+c.y,this.ignore_camera||(e-=c.camera_x,d-=c.camera_y),
e=a.x-e,d=a.y-d,b=this.radius,b*=b,a=e*e+d*d);return a<=b?this:null};function Bitmap(a,b,c){this.name=a;this.image=new Image;this.location=b;c&&(this.image.src=b)}Bitmap.prototype.load=function(){this.image.src=this.location};CanvasActor.prototype=new Actor;CanvasActor.prototype.constructor=CanvasActor;CanvasActor.prototype.parent=Actor.prototype;function CanvasActor(){this.scroll_vy=this.scroll_vx=this.scroll_pos_y=this.scroll_pos_x=this.prev_scroll_pos_y=this.prev_scroll_pos_x=0;this.scroll_range=[0,0,0,0];Actor.call(this);this.iscanvas=!0}
CanvasActor.prototype.onMoveTouchBase=function(a){this.touchmove=!0;if(this.bubbling&&null!=this.parent)this.parent.onMoveTouchBase(a);if(this.touching&&(0!=this.scroll_range[2]||0!=this.scroll_range[3])){var b=scene.app;this.prev_scroll_pos_x=this.scroll_pos_x;this.prev_scroll_pos_y=this.scroll_pos_y;this.scroll_vx=b.touch_drag_x;this.scroll_pos_x+=b.touch_drag_x;this.scroll_vy=b.touch_drag_y;this.scroll_pos_y+=b.touch_drag_y;if(0!=this.scroll_vx||0!=this.scroll_vy)this.scrollRangeCheck(),this.updateLayout()}if(void 0!=
this.onMoveTouch)this.onMoveTouch(a)};
CanvasActor.prototype.update=function(a){if(!this.touching){this.prev_scroll_pos_x=this.scroll_pos_x;this.prev_scroll_pos_y=this.scroll_pos_y;this.scroll_pos_x+=this.scroll_vx;this.scroll_pos_y+=this.scroll_vy;if(0!=this.scroll_vx||0!=this.scroll_vy)this.scrollRangeCheck(),this.updateLayout();this.scroll_vx*=.9;this.scroll_vy*=.9;-.5<this.scroll_vx&&.5>this.scroll_vx&&(this.scroll_vx=0);-.5<this.scroll_vy&&.5>this.scroll_vy&&(this.scroll_vy=0)}0==this.frame_count&&this.updateLayout();return this.baseUpdate(a)};
CanvasActor.prototype.scrollRangeCheck=function(){var a=this.scroll_pos_x,b=this.scroll_pos_y,c=-this.scroll_range[0],d=c-this.scroll_range[2],e=-this.scroll_range[1],f=e-this.scroll_range[3];a<d?(a=d,this.scroll_vx=0):a>c&&(a=c,this.scroll_vx=0);b<f?(b=f,this.scroll_vy=0):b>e&&(b=e,this.scroll_vy=0);this.scroll_pos_x=a;this.scroll_pos_y=b};
CanvasActor.prototype.updateLayout=function(a){a=this.prev_scroll_pos_x-this.scroll_pos_x;var b=this.prev_scroll_pos_y-this.scroll_pos_y,c=this.actors.length,d=this.w/2,e=this.h/2;if(0<c)for(var f,g=this.actors,h=0;h<c;h++)f=g[h],0!=f.dock_x?1==f.dock_x?f.x=-d+f.w/2+f.margin[0]:2==f.dock_x&&(f.x=d-f.w/2-f.margin[1]):f.x+=a,0!=f.dock_y?1==f.dock_y?f.y=-e+f.h/2+f.margin[2]:2==f.dock_y&&(f.y=e-f.h/2-f.margin[3]):f.y+=b,f.transform_dirty=!0};function Display(a){this.canvas=a;this.context=a.getContext("2d");this.canvas_width=a.width;this.canvas_height=a.height;this.screen_width=window.innerWidth;this.screen_height=window.innerHeight;this.context.lineWidth=1;this.context.strokeStyle="black";this.context.fillStyle="black";this.context.globalAlpha=1;this.context.lineJoin="round";this.context.lineCap="round";this.resize=function(){};window.addEventListener("resize",this.resize)}
Display.prototype.getCanvasPoint=function(a,b){return{x:a-this.canvas.offsetLeft,y:b-this.canvas.offsetTop}};Display.prototype.clear=function(a){a=this.context;a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,this.canvas_width,this.canvas_height)};Display.prototype.drawPolygon=function(a,b,c,d){var e=this.context,f=c.length;e.beginPath();e.moveTo(c[0]+a,c[1]+b);for(var g=2;g<f;g+=2)e.lineTo(c[g]+a,c[g+1]+b);d?e.fill():e.stroke();return this};
Display.prototype.drawLine=function(a,b,c,d){var e=this.context;e.beginPath();e.moveTo(a,b);e.lineTo(c,d);e.stroke();return this};Display.prototype.drawRect=function(a,b,c,d,e){var f=this.context;e?f.fillRect(a,b,c,d):f.strokeRect(a,b,c,d);return this};Display.prototype.drawArc=function(a,b,c,d,e,f){var g=this.context;g.beginPath();g.arc(a,b,c,d,e);f?g.fill():g.stroke();return this};Display.prototype.drawAtlasImage=function(a,b,c,d,e,f,g,h,l){this.context.drawImage(a,b,c,d,e,f,g,h,l)};
Display.prototype.drawImage=function(a,b,c,d,e){this.context.drawImage(a,b,c,d,e)};function Geometry(a){this.name=a;this.vertices=[]};function ImageAtlas(a,b,c,d,e,f){this.frames=[];this.name=a;this.bitmap=b;void 0!=c&&void 0!=d&&void 0!=e&&void 0!=f&&this.addFrame(c,d,e,f)}ImageAtlas.prototype.addFrame=function(a,b,c,d){this.frames.push({x:a,y:b,w:c,h:d})};ImageAtlas.prototype.getFrame=function(a){return this.frames[Math.floor(a)]};ImageAtlas.prototype.getMaxFrames=function(){return this.frames.length};
ImageAtlas.prototype.generate=function(a,b,c,d){for(var e=0,f=0;f<d;f++){for(var g=0,h=0;h<c;h++)this.addFrame(g,e,a,b),g+=a;e+=b}};LabelActor.prototype=new Actor;LabelActor.prototype.constructor=LabelActor;LabelActor.prototype.parent=Actor.prototype;function LabelActor(){this.text="";this.font="16pt Calibri";this.text_align="center";this.text_baseline="middle";this.fill_style="#ffffff";Actor.call(this);this.oy=this.ox=0}LabelActor.prototype.update=function(a){return this.baseUpdate(a)};
LabelActor.prototype.draw=function(){if(this.visible&&""!=this.text){var a=this.scene,b=app.display,c=b.context;c.font=this.font;""!=c.textAlign&&(c.textAlign=this.text_align);""!=c.textBaseline&&(c.textBaseline=this.text_baseline);""!=this.fill_style&&(c.fillStyle=this.fill_style);var d=b.canvas_width/2+a.x,b=b.canvas_height/2+a.y;this.accum_opacity=null!=this.parent&&this.use_parent_opacity?this.parent.accum_opacity*this.opacity:this.opacity*this.scene.opacity;c.globalAlpha=this.accum_opacity;if(this.use_transform){var e=
this.ox,f=this.oy;this.absolute_origin||(e*=this.w,f*=this.h);e=e+.5<<0;f=f+.5<<0;this.ignore_camera||0!=this.depth||(d-=a.camera_x,b-=a.camera_y);this.updateTransform();a=this.transform;c.setTransform(a[0],a[1],a[2],a[3],a[4]+d,a[5]+b);c.fillText(this.text,-e,-f)}else e=this.x,f=this.y,null!=this.parent&&(e+=this.parent.x,f+=this.parent.y),this.ignore_camera||(e-=a.camera_x,f-=a.camera_y),e=e+d+.5<<0,f=f+b+.5<<0,c.setTransform(1,0,0,1,0,0),c.fillText(this.text,e,f);c=this.actors.length;if(0<c)for(d=
this.actors,a=0;a<c;a++)d[a].draw()}};function Material(a){this.name=a;this.type="static";this.density=1;this.restitution=this.friction=.1;this.gravity_scale=1;this.is_bullet=this.fixed_rotation=!1};ParticleActor.prototype=new Actor;ParticleActor.prototype.constructor=ParticleActor;ParticleActor.prototype.parent=Actor.prototype;function ParticleActor(){Actor.call(this);this.gravity=0}
ParticleActor.prototype.resetParticle=function(a){a.life_time=0;a.x=a.org_x;a.y=a.org_y;a.rotation=a.org_rotation;a.scale_x=a.org_scale_x;a.scale_y=a.org_scale_y;a.depth=a.org_depth;a.opacity=a.org_opacity;a.current_frame=a.org_current_frame;a.vr=a.org_vr;a.vx=a.org_vx;a.vy=a.org_vy;a.vd=a.org_vd;a.vo=a.org_vo;a.vsx=a.org_vsx;a.vsy=a.org_vsy};
ParticleActor.prototype.addParticle=function(a,b,c,d){this.addActor(a);void 0==a.vo&&(a.vo=0);void 0==a.vsx&&(a.vsx=0);void 0==a.vsy&&(a.vsy=0);a.life_time=-d;a.life_span=b;a.num_lives=c;0>a.life_time&&(a.active=!1,a.visible=!1);a.org_num_lives=a.num_lives;a.org_x=a.x;a.org_y=a.y;a.org_rotation=a.rotation;a.org_scale_x=a.scale_x;a.org_scale_y=a.scale_y;a.org_depth=a.depth;a.org_opacity=a.opacity;a.org_current_frame=a.current_frame;a.org_vr=a.vr;a.org_vx=a.vx;a.org_vy=a.vy;a.org_vd=a.vd;a.org_vo=a.vo;
a.org_vsx=a.vsx;a.org_vsy=a.vsy};
ParticleActor.prototype.update=function(a){var b=this.actors,c=b.length;if(0==c)void 0!=this.OnParticlesEnd&&this.OnParticlesEnd(),this.destroy();else for(c-=1;0<=c;c--){var d=b[c];d.life_time+=a;var e=d.life_time;0<=e&&(0>e-a&&0<=e&&(d.active=!0,d.visible=!0),d.active&&(d.scale_x+=d.vsx*a,d.scale_y+=d.vsy*a,d.opacity+=d.vo*a,0>d.opacity&&(d.opacity=0),d.vy+=this.gravity*a,d.update(a),e>=d.life_span&&(0<d.num_lives&&d.num_lives--,0<d.num_lives||0==d.org_num_lives?this.resetParticle(d):(void 0!=this.OnParticleLost&&
this.OnParticleLost(d),d.destroy()))))}return this.baseUpdate(a)};ParticleActor.prototype.generateExplosion=function(a,b,c,d,e,f,g,h){for(var l=0;l<a;l++){var k=new b,m;for(m in h)k[m]=h[m];k.vr+=Math.random()*e;k.vx+=Math.random()*d-d/2;k.vy+=Math.random()*d-d/2;k.vx_damping=g;k.vy_damping=g;k.vo=-1/c;this.addParticle(k,c,1,l/(a*f))}};
ParticleActor.prototype.generatePlume=function(a,b,c,d,e,f,g,h){for(var l=0;l<a;l++){var k=new b,m;for(m in h)k[m]=h[m];k.vr+=Math.random()*e;k.vx+=Math.random()*d-d/2;k.vy+=Math.random()*-d-d/2;k.vx_damping=g;k.vy_damping=g;k.vo=-1/c;this.addParticle(k,c,0,l/(a*f))}};
ParticleActor.prototype.generateRain=function(a,b,c,d,e,f,g,h,l){for(var k=0;k<a;k++){var m=new b,n;for(n in l)m[n]=l[n];m.x=Math.random()*h-h/2;m.vr+=Math.random()*e;m.vy+=Math.random()*d+d/2;m.vx_damping=g;m.vy_damping=g;m.vo=-1/c;this.addParticle(m,c,0,k/(a*f))}};PolygonActor.prototype=new Actor;PolygonActor.prototype.constructor=PolygonActor;PolygonActor.prototype.parent=Actor.prototype;function PolygonActor(){this.stroke_style=this.fill_style="";this.filled=!0;this.points=null;Actor.call(this);this.oy=this.ox=0}PolygonActor.prototype.update=function(a){return this.baseUpdate(a)};
PolygonActor.prototype.draw=function(){if(this.visible&&null!=this.points){var a=this.scene,b=app.display,c=b.context;this.filled&&""!=this.fill_style&&(c.fillStyle=this.fill_style);this.filled||""==this.stroke_style||(c.strokeStyle=this.stroke_style);var d=b.canvas_width/2+a.x,e=b.canvas_height/2+a.y;this.accum_opacity=null!=this.parent&&this.use_parent_opacity?this.parent.accum_opacity*this.opacity:this.opacity*this.scene.opacity;c.globalAlpha=this.accum_opacity;if(this.use_transform){var f=this.ox,
g=this.oy;this.absolute_origin||(f*=this.w,g*=this.h);f=f+.5<<0;g=g+.5<<0;this.ignore_camera||0!=this.depth||(d-=a.camera_x,e-=a.camera_y);this.updateTransform();a=this.transform;c.setTransform(a[0],a[1],a[2],a[3],a[4]+d,a[5]+e);b.drawPolygon(-f,-g,this.points,this.filled);if(this.clip_children){c.save();c.setTransform(a[0],a[1],a[2],a[3],a[4]+d,a[5]+e);c.beginPath();b=this.points;c.moveTo(b[0]+h,b[1]+l);for(d=2;d<count;d+=2)c.lineTo(b[d]+h,b[d+1]+l);c.closePath();c.clip()}}else{var h=this.x,l=this.y;
null!=this.parent&&(h+=this.parent.x,l+=this.parent.y);this.ignore_camera||(h-=a.camera_x,l-=a.camera_y);h=h+d+.5<<0;l=l+e+.5<<0;c.setTransform(1,0,0,1,0,0);b.drawPolygon(h,l,this.points,this.filled);if(this.clip_children){c.save();c.beginPath();b=this.points;c.moveTo(b[0]+h,b[1]+l);for(d=2;d<count;d+=2)c.lineTo(b[d]+h,b[d+1]+l);c.closePath();c.clip()}}this.clip_children&&c.restore()}};RectActor.prototype=new Actor;RectActor.prototype.constructor=RectActor;RectActor.prototype.parent=Actor.prototype;function RectActor(){this.stroke_style=this.fill_style="";this.filled=!0;Actor.call(this)}RectActor.prototype.update=function(a){return this.baseUpdate(a)};
RectActor.prototype.draw=function(){if(this.visible){var a=this.scene,b=app.display,c=b.context;this.filled&&""!=this.fill_style&&(c.fillStyle=this.fill_style);this.filled||""==this.stroke_style||(c.strokeStyle=this.stroke_style);var d=b.canvas_width/2+a.x,e=b.canvas_height/2+a.y;this.accum_opacity=null!=this.parent&&this.use_parent_opacity?this.parent.accum_opacity*this.opacity:this.opacity*this.scene.opacity;c.globalAlpha=this.accum_opacity;if(this.use_transform){var f=this.ox,g=this.oy;this.absolute_origin||
(f*=this.w,g*=this.h);f=f+.5<<0;g=g+.5<<0;this.ignore_camera||0!=this.depth||(d-=a.camera_x,e-=a.camera_y);this.updateTransform();a=this.transform;c.setTransform(a[0],a[1],a[2],a[3],a[4]+d,a[5]+e);b.drawRect(-f,-g,this.w,this.h,this.filled);this.clip_children&&(c.save(),c.beginPath(),c.setTransform(a[0],a[1],a[2],a[3],a[4]+d,a[5]+e),c.rect(-f,-g,this.w,this.h),c.clip())}else f=this.x,g=this.y,null!=this.parent&&(f+=this.parent.x,g+=this.parent.y),this.ignore_camera||(f-=a.camera_x,g-=a.camera_y),
f=f+d+.5<<0,g=g+e+.5<<0,c.setTransform(1,0,0,1,0,0),b.drawRect(f,g,this.w,this.h,this.filled),this.clip_children&&(c.save(),c.beginPath(),c.rect(f,g,this.w,this.h),c.clip());b=this.actors.length;if(0<b)for(d=this.actors,e=0;e<b;e++)d[e].draw();this.clip_children&&c.restore()}};function Scene(){this.app=null;this.actors=[];this.removals=[];this.frame_count=0;this.tag=this.name="";this.visible=!0;this.y=this.x=0;this.w=1024;this.h=768;this.clip_children=!0;this.clip_shape=null;this.camera_vy=this.camera_vx=this.camera_y=this.camera_x=0;this.follow_speedy=this.follow_speedx=.3;this.targety=this.targetx=null;this.touch_pan_y=this.touch_pan_x=!1;this.world=null;this.world_scale=20;this.extents=[0,0,0,0];this.opacity=1;this.touchmove=this.touching=!1;this.timelines=new TimelineManager;
this.bitmaps=[];this.brushes=[];this.shapes=[];this.materials=[];this.geoms=[];this.sounds=[]}Scene.prototype.release=function(){if(void 0!=this.onDestroy)this.onDestroy();this.actors=this.world=null};Scene.prototype.addActor=function(a){this.actors.push(a);a.scene=this};Scene.prototype.removeActor=function(a){this.removals.push(a)};Scene.prototype.removeActorsWithTag=function(a){for(var b=this.actors,c=b.length,d=this.removals,e=0;e<c;e++)b[e].tag==a&&d.push(b[e])};
Scene.prototype.cleanupDestroyedActors=function(){var a=this.removals.length;if(0<a)for(var b=this.removals,c=this.actors,d=c.length,e=0;e<a;e++)for(var f=b[e],g=0;g<d;g++)if(f==c[g]){f.release();c.splice(g,1);d--;break}this.removals=[]};Scene.prototype.findActor=function(a){for(var b=this.actors,c=b.length,d=0;d<c;d++)if(b[d].name==a)return b[d];return null};
Scene.prototype.findActorDeep=function(a){for(var b=this.actors,c=b.length,d=0;d<c;d++){if(b[d].name==a)return b[d];var e=b[d].findActorDeep(a);if(null!=e)return e}return null};Scene.prototype.bringToFront=function(a){this.removeActor(a,!1);this.addActor(a)};Scene.prototype.onBeginTouchBase=function(a){this.touching=!0;if(void 0!=this.onBeginTouch)this.onBeginTouch(a)};
Scene.prototype.onEndTouchBase=function(a){if(this.touching&&void 0!=this.onTapped)this.onTapped(a);this.touchmove=this.touching=!1;if(void 0!=this.onEndTouch)this.onEndTouch(a)};
Scene.prototype.onMoveTouchBase=function(a){this.touchmove=!0;if(void 0!=this.onMoveTouch)this.onMoveTouch(a);if(this.touching){a=this.app;if(this.touch_pan_x){var b=a.touch_drag_x;this.camera_vx=b*a.target_frame_rate;this.camera_x+=b}this.touch_pan_y&&(b=a.touch_drag_y,this.camera_vy=b*a.target_frame_rate,this.camera_y+=b)}};
Scene.prototype.initWorld=function(a,b,c){this.world=new Box2D.Dynamics.b2World(new Box2D.Common.Math.b2Vec2(a,b),c);a=new Box2D.Dynamics.b2ContactListener;a.BeginContact=function(a){var b=a.GetFixtureA().GetBody().GetUserData();if(void 0!=b.onCollisionStart)b.onCollisionStart(a)};a.EndContact=function(a){var b=a.GetFixtureA().GetBody().GetUserData();if(void 0!=b.onCollisionEnd)b.onCollisionEnd(a)};this.world.SetContactListener(a)};
Scene.prototype.draw=function(){if(this.visible){var a=app.display.context;if(this.clip_children){a.setTransform(1,0,0,1,0,0);a.save();a.beginPath();if(null==this.clip_shape)a.rect(this.x+.5<<0,this.y+.5<<0,this.w,this.h);else{var b=app.display,c=this.x+b.canvas_width/2+.5<<0,d=this.y+b.canvas_height/2+.5<<0,b=this.clip_shape;if(this.clip_shape.type==Shape.TypeBox)a.rect(c,d,b.width,b.height);else if(this.clip_shape.type==Shape.TypeCircle)a.arc(c,d,b.width,0,2*Math.PI,!1);else if(this.clip_shape.type==
Shape.TypePolygon){var e=b.vertices,b=e.length;a.moveTo(e[0]+c,e[1]+d);for(var f=2;f<b;f+=2)a.lineTo(e[f]+c,e[f+1]+d);a.closePath()}}a.clip()}c=this.actors;b=c.length;for(d=0;d<b;d++)c[d].draw();this.clip_children&&a.restore()}};
Scene.prototype.baseUpdate=function(a){if(void 0!=this.onTick)this.onTick(a);if(!this.visible)return!1;this.timelines.update(a);this.updateCamera(a);null!=this.world&&this.world.Step(1/this.app.target_frame_rate,10,10);for(var b=this.actors,c=b.length,d=0;d<c;d++)b[d].update(a);null!=this.world&&this.world.ClearForces();this.frame_count++;this.cleanupDestroyedActors();return!0};Scene.prototype.update=function(a){return this.baseUpdate(a)};
Scene.prototype.updateCamera=function(a){null!=this.targetx&&(0==this.follow_speedx?(this.camera_x=this.targetx.x,this.camera_vx=0):this.camera_vx+=(this.targetx.x-this.camera_x)*this.follow_speedx);null!=this.targety&&(0==this.follow_speedy?(this.camera_y=this.targety.y,this.camera_vy=0):this.camera_vy+=(this.targety.y-this.camera_y)*this.follow_speedy);this.touching||(this.camera_x+=this.camera_vx*a,this.camera_y+=this.camera_vy*a,this.camera_vx*=.9,this.camera_vy*=.9);if(0!=this.camera_x||0!=this.camera_y){var b=
this.app.display.canvas_width;a=this.app.display.canvas_height;if(b<=this.extents[2]&&a<=this.extents[3]){var c=b/2,b=this.extents[0]+c,c=this.extents[0]+this.extents[2]-c;this.camera_x<b&&(this.camera_x=b,this.camera_vx=0);this.camera_x>c&&(this.camera_x=c,this.camera_vx=0);b=a/2;a=this.extents[1]+b;b=this.extents[1]+this.extents[3]-b;this.camera_y<a&&(this.camera_y=a,this.camera_vy=0);this.camera_y>b&&(this.camera_y=b,this.camera_vy=0)}}};
Scene.prototype.findHitActor=function(a){for(var b=this.actors,c=null,d=b.length-1;0<=d&&(c=b[d].hitTest(a),null==c);d--);return c};Scene.prototype.addResource=function(a,b){var c;if("brush"==b)c=this.brushes;else if("sound"==b)c=this.sounds;else if("shape"==b)c=this.shapes;else if("material"==b)c=this.materials;else if("bitmap"==b)c=this.bitmaps;else if("geometry"==b)c=this.geoms;else return;c.push(a)};
Scene.prototype.findResource=function(a,b){var c;if("brush"==b)c=this.brushes;else if("sound"==b)c=this.sounds;else if("shape"==b)c=this.shapes;else if("material"==b)c=this.materials;else if("bitmap"==b)c=this.bitmaps;else if("geometry"==b)c=this.geoms;else return null;for(var d=c.length,e=0;e<d;e++)if(c[e].name==a)return c[e];return this.app.findResource(a,b)};function Shape(a){this.name=a;this.type=Shape.TypeBox;this.height=this.width=0;this.vertices=[]}Shape.TypeBox=0;Shape.TypeCircle=1;Shape.TypePolygon=2;Shape.prototype.typeToConst=function(a){return"polygon"==shape.type?Shape.TypePolygon:"circle"==shape.type?Shape.TypeCircle:Shape.TypeBox};function Sound(a,b){this.name=a;this.location=b}Sound.prototype.play=function(){var a=new Audio(this.location);a.play();return a};function Xoml(a){this.current_scene=null;this.app=a}Xoml.prototype.loadJSON=function(a){$.getJSON(a,function(a){window.game.parseResources(a)})};Xoml.prototype.loadJS=function(a){var b=document.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("src",a);"undefined"!=typeof b&&document.getElementsByTagName("head")[0].appendChild(b)};
Xoml.prototype.parseScene=function(a,b){this.app.debug&&console.log("Parsing Scene "+b.Name);var c=new Scene;this.current_scene=c;c.name=b.Name;void 0!=b.Tag&&(c.tag=b.Tag);c.x=b.Position.x;c.y=b.Position.y;void 0!=b.Layer&&(c.layer=b.Layer);c.visible=b.Visible;c.active=b.Active;b.Physics&&c.initWorld(b.Gravity.x,b.Gravity.y,b.DoSleep);void 0!=b.ClipChildren&&(c.clip_children=b.ClipChildren);"Both"==b.TouchPan?(c.touch_pan_x=!0,c.touch_pan_y=!0):"X"==b.TouchPan?c.touch_pan_x=!0:"Y"==b.TouchPan&&(c.touch_pan_y=
!0);c.extents[0]=b.Extents.x;c.extents[1]=b.Extents.y;c.extents[2]=b.Extents.w;c.extents[3]=b.Extents.h;c.follow_speedx=b.FollowSpeed.x;c.follow_speedy=b.FollowSpeed.y;a.addScene(c);b.Current&&(a.focus_scene=c);var d=b.UserProps;if(void 0!==d)for(var e=0;e<d.length;e++)actor[d[e].Name]=d[e].Value;void 0!=b.Alpha&&(c.opacity=b.Alpha);void 0!==b.Children&&this.parseResources(c,b.Children);void 0!=b.ClipShape&&""!=b.ClipShape&&(c.clip_shape=c.findResource(b.ClipShape,"shape"));""!=b.TargetX&&(c.target_x=
c.findActor(b.TargetX));""!=b.TargetY&&(c.target_y=c.findActor(b.TargetY));void 0!=b.OnCreate&&(c.onCreate=function(a){eval(b.OnCreate)});void 0!=b.OnDestroy&&(c.onDestroy=function(a){eval(b.OnDestroy)});void 0!=b.OnTick&&(c.onTick=function(a){eval(b.OnTick)});void 0!=b.OnTapped&&(c.onTapped=function(a){eval(b.OnTapped)});void 0!=b.OnBeginTouch&&(c.onBeginTouch=function(a){eval(b.OnBeginTouch)});void 0!=b.OnEndTouch&&(c.onEndTouch=function(a){eval(b.OnEndTouch)});void 0!=b.OnMoveTouch&&(c.onMoveTouch=
function(a){eval(b.OnMoveTouch)});if(void 0!=c.onCreate)c.onCreate()};Xoml.prototype.parseBrush=function(a,b){this.app.debug&&console.log("Parsing Brush "+b.Name);var c=b.Rect,d=a.findResource(b.Image,"bitmap"),c=new ImageAtlas(b.Name,d,c.x,c.y,c.w,c.h);a.addResource(c,"brush")};Xoml.prototype.parseImage=function(a,b){this.app.debug&&console.log("Parsing Image "+b.Name);var c=new Bitmap(b.Name,b.Location,b.Preload);a.addResource(c,"bitmap")};
Xoml.prototype.parseSound=function(a,b){this.app.debug&&console.log("Parsing Sound "+b.Name);var c=new Sound(b.Name,b.Location);a.addResource(c,"sound")};Xoml.prototype.parseFont=function(a,b){this.app.debug&&console.log("Parsing Font "+b.Name)};
Xoml.prototype.parseShape=function(a,b){this.app.debug&&console.log("Parsing Shape "+b.Name);var c=new Shape(b.Name);c.width=b.Width;c.height=b.Height;if("Circle"==b.ShapeType)c.type=Shape.TypeCircle;else if("Box"==b.ShapeType)c.type=Shape.TypeBox;else if("Polygon"==b.ShapeType){c.type=Shape.TypePolygon;for(var d=b.Vertices,e=d.length,f=0;f<e;f++)c.vertices.push(d[f])}a.addResource(c,"shape")};
Xoml.prototype.parseMaterial=function(a,b){this.app.debug&&console.log("Parsing Material "+b.Name);var c=new Material;c.name=b.Name;c.type=b.MaterialType;c.density=b.Density;c.friction=b.Friction;c.restitution=b.Restitution;c.gravity_scale=b.GravityScale;c.fixed_rotation=b.FixedRotation;c.is_bullet=b.IsBullet;a.addResource(c,"material")};
Xoml.prototype.parseGeometry=function(a,b){this.app.debug&&console.log("Parsing Geometry "+b.Name);var c=new Geometry;c.name=b.Name;for(var d=b.Vertices,e=d.length,f=0;f<e;f++)c.vertices.push(d[f]);a.addResource(c,"geometry")};
Xoml.prototype.parseActor=function(a,b,c){this.app.debug&&console.log("Parsing Actor "+c.Name);a.scene=this.current_scene;void 0!=c.Name&&(a.name=c.Name);void 0!=c.Tag&&(a.tag=c.Tag);void 0!=c.Visible&&(a.visible=c.Visible);void 0!=c.Active&&(a.active=c.Active);void 0!=c.Layer&&(a.layer=c.Layer);void 0!=c.Background&&(a.atlas=this.current_scene.findResource(c.Background,"brush"));void 0!=c.Position&&(a.x=c.Position.x,a.y=c.Position.y);void 0!=c.Scale&&(a.scale_x=c.Scale.x,a.scale_y=c.Scale.y);void 0!=
c.FlipX&&c.FlipX&&(a.scale_x=-a.scale_x);void 0!=c.FlipY&&c.FlipY&&(a.scale_y=-a.scale_y);void 0!=c.Angle&&(a.rotation=c.Angle);void 0!=c.Size&&(a.w=c.Size.x,a.h=c.Size.y);void 0!=c.Origin&&(a.ox=c.Origin.x,a.oy=c.Origin.y);if(-1>=a.ox||1<=a.ox||-1>=a.oy||1<=a.oy)a.absolute_origin=!0;void 0!=c.Alpha&&(a.opacity=c.Alpha);void 0!=c.UseParentOpacity&&(a.use_parent_opacity=c.UseParentOpacity);void 0!=c.Depth&&(a.depth=c.Depth);a.use_transform=!0;void 0!=c.Velocity&&(a.vx=c.Velocity.x,a.vy=c.Velocity.y);
void 0!=c.AngularVelocity&&(a.vr=c.AngularVelocity);void 0!=c.VelocityDamping&&(a.vx_damping=c.VelocityDamping.x,a.vy_damping=c.VelocityDamping.y);void 0!=c.AngularVelocityDamping&&(a.vr_damping=c.AngularVelocityDamping);void 0!=c.WrapPosition&&(a.wrap_position=c.WrapPosition);void 0!=c.IgnoreCamera&&(a.ignore_camera=c.IgnoreCamera);void 0!=c.ClipChildren&&(a.clip_children=c.ClipChildren);void 0!=c.Touchable&&(a.touchable=c.Touchable);void 0!=c.Bubbling&&(a.bubbling=c.Bubbling);if(void 0!=c.Docking){var d=
c.Docking;if("top"==d||"topleft"==d||"topright"==d)a.dock_y=1;else if("bottom"==d||"bottomleft"==d||"bottomright"==d)a.dock_y=2;if("left"==d||"topleft"==d||"bottomleft"==d)a.dock_x=1;else if("right"==d||"topright"==d||"bottomright"==d)a.dock_x=2}void 0!=c.Margin&&(a.margin[0]=c.Margin.x,a.margin[1]=c.Margin.y,a.margin[2]=c.Margin.w,a.margin[3]=c.Margin.h);void 0!=c.ClipMargin&&(a.clip_margin[0]=c.ClipMargin.x,a.clip_margin[1]=c.ClipMargin.y,a.clip_margin[2]=c.ClipMargin.w,a.clip_margin[3]=c.ClipMargin.h);
b.addActor(a);void 0!=c.OnCreate&&(a.onCreate=function(a){eval(c.OnCreate)});void 0!=c.OnDestroy&&(a.onDestroy=function(a){eval(c.OnDestroy)});void 0!=c.OnTick&&(a.onTick=function(a){eval(c.OnTick)});void 0!=c.OnTapped&&(a.touchable=!0,a.onTapped=function(a){eval(c.OnTapped)});void 0!=c.OnBeginTouch&&(a.touchable=!0,a.onBeginTouch=function(a){eval(c.OnBeginTouch)});void 0!=c.OnEndTouch&&(a.touchable=!0,a.onEndTouch=function(a){eval(c.OnEndTouch)});void 0!=c.OnMoveTouch&&(a.touchable=!0,a.onMoveTouch=
function(a){eval(c.OnMoveTouch)});void 0!=c.OnCollisionStart&&(a.onCollisionStart=function(a){eval(c.OnCollisionStart)});void 0!=c.OnCollisionEnd&&(a.onCollisionEnd=function(a){eval(c.OnCollisionEnd)});d=c.UserProps;if(void 0!==d)for(b=0;b<d.length;b++)a[d[b].Name]=d[b].Value;var e=c.Fixtures;if(void 0!==e)for(b=0;b<e.length;b++){var d=[],f=null,g=null;void 0!=e[b].Material&&""!=e[b].Material&&(f=this.current_scene.findResource(e[b].Material,"material"));void 0!=e[b].Shape&&""!=e[b].Shape&&(g=this.current_scene.findResource(e[b].Shape,
"shape"));0==b&&a.initBody(f.type,f.fixed_rotation,f.is_bullet);null==g?1==c.RenderAs?(d.type=Shape.TypeCircle,d.radius=a.w/2):(d.type=Shape.TypeBox,d.width=a.w,d.height=a.h):(g.type==Shape.TypePolygon?d.points=g.vertices:g.type==Shape.TypeCircle?d.radius=g.width:(d.width=g.width,d.height=g.height),d.type=g.type);null!=f&&(d.density=f.density,d.friction=f.friction,d.restitution=f.restitution);d.is_sensor=e[b].Sensor;a.addFixture(d)}e=c.Joints;if(void 0!==e)for(b=0;b<e.length;b++)d=[],f=this.current_scene.findActor(e[b].ActorB),
d.type=e[b].Type,d.actor_b=f,d.anchor_a=e[b].OffsetA,d.anchor_b=e[b].OffsetB,d.self_collide=e[b].SelfCollide,d.damping=e[b].Damping,d.frequency=e[b].Frequency,d.limit_joint=e[b].LimitJoint,d.lower_limit=e[b].LowerLimit,d.upper_limit=e[b].UpperLimit,d.motor_enabled=e[b].MotorEnabled,d.motor_speed=e[b].MotorSpeed,d.max_motor_torque=e[b].MaxMotorTorque,d.max_motor_force=e[b].MaxMotorForce,d.ground_a=e[b].GroundA,d.ground_b=e[b].GroundB,d.axis=e[b].Axis,d.ratio=e[b].Ratio,a.addJoint(d);null!=a.body&&
(a.body.SetLinearVelocity(new Box2D.Common.Math.b2Vec2(a.vx,a.vy)),a.body.SetAngularVelocity(a.vr),a.body.SetLinearDamping(a.vx_damping),a.body.SetAngularDamping(a.vr_damping));void 0!==c.Children&&this.parseResources(a,c.Children)};
Xoml.prototype.parseIcon=function(a,b){this.app.debug&&console.log("Parsing Icon "+b.Name);var c,d=0;void 0!=b.RenderAs&&(d=b.RenderAs);if(1==d)c=new ArcActor,void 0!=b.Colour&&(c.fill_style=b.Colour);else if(2==d)c=new RectActor,void 0!=b.Colour&&(c.fill_style=b.Colour);else if(0==d)if(void 0!==b.Geometry){c=new PolygonActor;var e=this.current_scene.findResource(b.Geometry,"geometry");c.points=e.vertices;void 0!=b.Colour&&(c.fill_style=b.Colour)}else c=void 0!=b.UIType&&1==b.UIType?new CanvasActor:
new Actor;this.parseActor(c,a,b);1==d&&(c.radius=c.w/2);void 0!=b.UIType&&1==b.UIType&&(void 0!=b.ScrollRange&&(c.scroll_range[0]=b.ScrollRange.x,c.scroll_range[1]=b.ScrollRange.y,c.scroll_range[2]=b.ScrollRange.w,c.scroll_range[3]=b.ScrollRange.h),void 0!=b.ScrollPos&&(c.scroll_pos_x=b.ScrollPos.x,c.scroll_pos_y=b.ScrollPos.y));if(void 0!=c.onCreate)c.onCreate()};
Xoml.prototype.parseLabel=function(a,b){this.app.debug&&console.log("Parsing Label "+b.Name);var c=new LabelActor;c.text=b.Text;c.font=b.Font;this.parseActor(c,a,b);if(void 0!=c.onCreate)c.onCreate()};
Xoml.prototype.parseResources=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=b[d].ResourceType;"Scene"==e?this.parseScene(a,b[d]):"Brush"==e?this.parseBrush(a,b[d]):"Image"==e?this.parseImage(a,b[d]):"Sound"==e?this.parseSound(a,b[d]):"Font"==e?this.parseFont(a,b[d]):"Shape"==e?this.parseShape(a,b[d]):"Material"==e?this.parseMaterial(a,b[d]):"Geometry"==e?this.parseGeometry(a,b[d]):"Icon"==e?this.parseIcon(a,b[d]):"Label"==e&&this.parseLabel(a,b[d])}};