/**
 * author       Mat Hopwood
 * copyright    2014 Mat Hopwood
 * More info    http://booty5.com
 */
function Actor(virtual){this.type=Actor.Type_Image;this.scene=null;this.parent=null;this.actors=[];this.removals=[];this.joints=[];this.frame_count=0;this.accum_scale_x=1;this.accum_scale_y=1;this.accum_opacity=1;this.body=null;this.transform=[];this.transform_dirty=true;this.touching=false;this.touchmove=false;this.layer=0;this.order_changed=true;this.cache=false;this.cache_canvas=null;this.name="";this.tag="";this.id=-1;this.active=true;this.visible=true;this.touchable=false;this.layer=0;this.x=
    0;this.y=0;this.w=0;this.h=0;this.ox=0;this.oy=0;this.absolute_origin=true;this.rotation=0;this.scale_x=1;this.scale_y=1;this.depth=0;this.opacity=1;this.use_parent_opacity=true;this.current_frame=0;this.frame_speed=0;this.anim_frames=null;this.bitmap=null;this.atlas=null;this.vr=0;this.vx=0;this.vy=0;this.vd=0;this.vr_damping=1;this.vx_damping=1;this.vy_damping=1;this.vd_damping=1;this.ignore_camera=false;this.wrap_position=false;this.dock_x=0;this.dock_y=0;this.margin=[0,0,0,0];this.bubbling=false;
    this.clip_children=false;this.clip_margin=[0,0,0,0];this.clip_shape=null;this.self_clip=false;this.orphaned=false;this.virtual=false;this.shadow=false;this.shadow_x=0;this.shadow_y=0;this.shadow_blur=0;this.shadow_colour="#000000";this.composite_op=null;if(virtual==true)this.makeVirtual()}Actor.Dock_None=0;Actor.Dock_Top=1;Actor.Dock_Bottom=2;Actor.Dock_Left=1;Actor.Dock_Right=2;Actor.Type_Image=0;Actor.Type_Label=1;Actor.Type_Rect=2;Actor.Type_Arc=3;Actor.Type_Polygon=4;Actor.Type_Particle=5;
Object.defineProperty(Actor.prototype,"_x",{get:function(){return this.x},set:function(value){if(this.x!=value){this.x=value;this.transform_dirty=true}}});Object.defineProperty(Actor.prototype,"_y",{get:function(){return this.y},set:function(value){if(this.y!=value){this.y=value;this.transform_dirty=true}}});Object.defineProperty(Actor.prototype,"_ox",{get:function(){return this.ox},set:function(value){if(this.ox!=value){this.ox=value;this.transform_dirty=true}}});
Object.defineProperty(Actor.prototype,"_oy",{get:function(){return this.oy},set:function(value){if(this.oy!=value){this.oy=value;this.transform_dirty=true}}});Object.defineProperty(Actor.prototype,"_rotation",{get:function(){return this.rotation},set:function(value){if(this.rotation!=value){this.rotation=value;this.transform_dirty=true}}});
Object.defineProperty(Actor.prototype,"_scale_x",{get:function(){return this.scale_x},set:function(value){if(this.scale_x!=value){this.scale_x=value;this.transform_dirty=true}}});Object.defineProperty(Actor.prototype,"_scale_y",{get:function(){return this.scale_y},set:function(value){if(this.scale_y!=value){this.scale_y=value;this.transform_dirty=true}}});Object.defineProperty(Actor.prototype,"_scale",{set:function(value){this._scale_x=value;this._scale_y=value}});
Object.defineProperty(Actor.prototype,"_depth",{get:function(){return this.depth},set:function(value){if(this.depth!=value){this.depth=value;this.transform_dirty=true}}});Object.defineProperty(Actor.prototype,"_layer",{get:function(){return this.layer},set:function(value){if(this.layer!=value){this.layer=value;if(this.parent!=null)this.parent.order_changed=true;else this.scene.order_changed=true}}});
Actor.prototype.setPosition=function(x,y){if(this.x!=x||this.y!=y){this.x=x;this.y=y;this.transform_dirty=true}};Actor.prototype.setPositionPhysics=function(x,y){if(this.body!=null){this.x=x;this.y=y;this.transform_dirty=true;var b2Vec2=Box2D.Common.Math.b2Vec2;var ws=this.scene.world_scale;this.body.SetPosition(new b2Vec2(x/ws,y/ws))}};Actor.prototype.setOrigin=function(x,y){if(this.ox!=x||this.oy!=y){this.ox=x;this.oy=y;this.transform_dirty=true}};
Actor.prototype.setScale=function(x,y){if(this.scale_x!=x||this.scale_y!=y){this.scale_x=x;this.scale_y=y;this.transform_dirty=true}};Actor.prototype.setRotation=function(angle){if(this.rotation!=angle){this.rotation=angle;this.transform_dirty=true;if(this.body!=null)this.body.SetAngle(angle)}};Actor.prototype.setRotationPhysics=function(angle){if(this.body!=null){this.rotation=angle;this.transform_dirty=true;this.body.SetAngle(angle)}};
Actor.prototype.setDepth=function(depth){if(this.depth!=depth){this.depth=depth;this.transform_dirty=true}};Actor.prototype.release=function(){if(this.onDestroy!==undefined)this.onDestroy();this.releaseJoints();this.releaseBody()};Actor.prototype.destroy=function(){if(this.parent!=null)this.parent.removeActor(this);else if(this.scene!=null)this.scene.removeActor(this)};
Actor.prototype.changeParent=function(parent){var acts;if(this.parent!=null)acts=this.parent.actors;else acts=this.scene.actors;var count=acts.length;for(var t=0;t<count;t++)if(this==acts[t]){acts.splice(t,1);parent.addActor(this);break}};Actor.prototype.addActor=function(actor){this.actors.push(actor);actor.parent=this;actor.scene=this.scene;return actor};Actor.prototype.removeActor=function(actor){this.removals.push(actor)};
Actor.prototype.removeActorsWithTag=function(tag){var acts=this.actors;var count=acts.length;var removals=this.removals;for(var t=0;t<count;t++)if(acts[t].tag==tag)removals.push(acts[t])};
Actor.prototype.cleanupDestroyedActors=function(){var dcount=this.removals.length;if(dcount>0){var removals=this.removals;var acts=this.actors;var count=acts.length;for(var s=0;s<dcount;s++){var dact=removals[s];for(var t=0;t<count;t++)if(dact==acts[t]){dact.release();acts.splice(t,1);count--;break}}}this.removals=[]};
Actor.prototype.findActor=function(name,recursive){if(recursive==undefined)recursive=false;var acts=this.actors;var count=acts.length;for(var t=0;t<count;t++)if(acts[t].name==name)return acts[t];else if(recursive){var act=acts[t].findActor(name,recursive);if(act!=null)return act}return null};Actor.prototype.findFirstParent=function(){var ach=this;while(ach!=null){if(ach.parent==null)return ach;ach=ach.parent}return null};
Actor.prototype.updateParentTransforms=function(){var parents=[];var ach=this;while(ach!=null){parents.push(ach);ach=ach.parent}for(var t=parents.length-1;t>=0;t--)parents[t].updateTransform()};Actor.prototype.bringToFront=function(){var acts;if(this.parent!=null)acts=this.parent.actors;else acts=this.scene.actors;var count=acts.length;var i=-1;for(var t=0;t<count;t++)if(acts[t]==this){i=t;break}if(i>=0){acts.splice(i,1);acts.push(this)}};
Actor.prototype.sendToBack=function(){var acts;if(this.parent!=null)acts=this.parent.actors;else acts=this.scene.actors;var count=acts.length;var i=-1;for(var t=0;t<count;t++)if(acts[t]==this){i=t;break}if(i>=0){acts.splice(i,1);acts.unshift(this)}};Actor.prototype.onBeginTouchBase=function(touch_pos){this.touching=true;if(this.bubbling&&this.parent!=null)this.parent.onBeginTouchBase(touch_pos);if(this.onBeginTouch!==undefined)this.onBeginTouch(touch_pos)};
Actor.prototype.onEndTouchBase=function(touch_pos){if(this.touching&&this.onTapped!==undefined)this.onTapped(touch_pos);this.touching=false;this.touchmove=false;if(this.bubbling&&this.parent!=null)this.parent.onEndTouchBase(touch_pos);if(this.onEndTouch!==undefined)this.onEndTouch(touch_pos)};
Actor.prototype.onMoveTouchBase=function(touch_pos){this.touchmove=true;if(this.bubbling&&this.parent!=null)this.parent.onMoveTouchBase(touch_pos);if(this.virtual)this.Virtual_onMoveTouch(touch_pos);if(this.onMoveTouch!==undefined)this.onMoveTouch(touch_pos)};Actor.prototype.releaseBody=function(){if(this.body!=null){this.scene.world.DestroyBody(this.body);this.body=null}};
Actor.prototype.releaseJoints=function(){if(this.body!=null){for(var t=0;t<this.joints.length;t++)this.scene.world.DestroyJoint(this.joints[t]);this.joints=null}};
Actor.prototype.initBody=function(body_type,fixed_rotation,is_bullet){if(!this.scene.app.box2d)return;var scene=this.scene;var body_def=new Box2D.Dynamics.b2BodyDef;var ws=scene.world_scale;if(body_type=="static")body_def.type=Box2D.Dynamics.b2Body.b2_staticBody;else if(body_type=="kinematic")body_def.type=Box2D.Dynamics.b2Body.b2_kinematicBody;else body_def.type=Box2D.Dynamics.b2Body.b2_dynamicBody;body_def.position.Set(this.x/ws,this.y/ws);body_def.angle=this.rotation;body_def.fixedRotation=fixed_rotation;
    body_def.bullet=is_bullet;this.body=scene.world.CreateBody(body_def);this.body.SetUserData(this)};
Actor.prototype.addFixture=function(options){if(this.body==null)return null;var fix_def;var ws=this.scene.world_scale;if(options.type==Shape.TypeBox){fix_def=new Box2D.Dynamics.b2FixtureDef;fix_def.shape=new Box2D.Collision.Shapes.b2PolygonShape;fix_def.shape.SetAsBox(options.width/(2*ws),options.height/(2*ws))}else if(options.type==Shape.TypeCircle){fix_def=new Box2D.Dynamics.b2FixtureDef;fix_def.shape=new Box2D.Collision.Shapes.b2CircleShape(options.radius/ws)}else if(options.type==Shape.TypePolygon)if(options.convexPoints!==
    undefined){var fixture_defs=[];var pc=options.convexPoints.length;for(var s=0;s<pc;s++){fix_def=new Box2D.Dynamics.b2FixtureDef;fix_def.shape=new Box2D.Collision.Shapes.b2PolygonShape;var points=options.convexPoints[s];var verts=[];var count=points.length;for(var t=0;t<count;t+=2)verts.push({x:points[t]/ws,y:points[t+1]/ws});fix_def.shape.SetAsArray(verts,verts.length);if(options.density!==undefined)fix_def.density=options.density;if(options.friction!==undefined)fix_def.friction=options.friction;
    if(options.restitution!==undefined)fix_def.restitution=options.restitution;if(options.is_sensor!==undefined)fix_def.isSensor=options.is_sensor;fixture_defs.push(this.body.CreateFixture(fix_def))}return fixture_defs}else{fix_def=new Box2D.Dynamics.b2FixtureDef;fix_def.shape=new Box2D.Collision.Shapes.b2PolygonShape;var points=options.points;var verts=[];var count=points.length;for(var t=0;t<count;t+=2)verts.push({x:points[t]/ws,y:points[t+1]/ws});fix_def.shape.SetAsArray(verts,verts.length)}if(options.density!==
    undefined)fix_def.density=options.density;if(options.friction!==undefined)fix_def.friction=options.friction;if(options.restitution!==undefined)fix_def.restitution=options.restitution;if(options.is_sensor!==undefined)fix_def.isSensor=options.is_sensor;return this.body.CreateFixture(fix_def)};
Actor.prototype.addJoint=function(options){if(this.body==null)return null;var joint_def;var scene=this.scene;var world=scene.world;var ws=scene.world_scale;var b2Vec2=Box2D.Common.Math.b2Vec2;var body_a=this.body;var body_b=options.actor_b.body;var body_a_centre=body_a.GetWorldCenter();var body_b_centre=body_b.GetWorldCenter();var lpa=new b2Vec2(body_a_centre.x,body_a_centre.y);lpa.x+=options.anchor_a.x/ws;lpa.y+=options.anchor_a.y/ws;var lpb=new b2Vec2(body_b_centre.x,body_b_centre.y);lpb.x+=options.anchor_b.x/
    ws;lpb.y+=options.anchor_b.y/ws;if(options.type=="weld"){joint_def=new Box2D.Dynamics.Joints.b2WeldJointDef;joint_def.Initialize(body_a,body_b,lpa);joint_def.collideConnected=options.self_collide}else if(options.type=="distance"){joint_def=new Box2D.Dynamics.Joints.b2DistanceJointDef;joint_def.Initialize(body_a,body_b,lpa,lpb);joint_def.collideConnected=options.self_collide;joint_def.frequencyHz=options.frequency;joint_def.dampingRatio=options.damping}else if(options.type=="revolute"){joint_def=new Box2D.Dynamics.Joints.b2RevoluteJointDef;
    joint_def.Initialize(body_a,body_b,lpa);joint_def.collideConnected=options.self_collide;if(options.limit_joint){joint_def.enableLimit=true;joint_def.lowerAngle=options.lower_limit*(Math.PI/180);joint_def.upperAngle=options.upper_limit*(Math.PI/180)}if(options.motor_enabled){joint_def.enableMotor=true;joint_def.motorSpeed=options.motor_speed;joint_def.maxMotorTorque=options.max_motor_torque}}else if(options.type=="prismatic"){joint_def=new Box2D.Dynamics.Joints.b2PrismaticJointDef;joint_def.Initialize(body_a,
    body_b,lpa,new b2Vec2(options.axis.x,options.axis.y));joint_def.collideConnected=options.self_collide;if(options.limit_joint){joint_def.enableLimit=true;joint_def.lowerTranslation=options.lower_limit/ws;joint_def.upperTranslation=options.upper_limit/ws}if(options.motor_enabled){joint_def.enableMotor=true;joint_def.motorSpeed=options.motor_speed;joint_def.maxMotorForce=options.max_motor_force}}else if(options.type=="pulley"){var ga=new b2Vec2(body_a_centre.x,body_a_centre.y);ga.x+=options.ground_a.x/
    ws;ga.y+=options.ground_a.y/ws;var gb=new b2Vec2(body_b_centre.x,body_b_centre.y);gb.x+=options.ground_b.x/ws;gb.y+=options.ground_b.y/ws;joint_def=new Box2D.Dynamics.Joints.b2PulleyJointDef;joint_def.Initialize(body_a,body_b,ga,gb,lpa,lpb,options.ratio);joint_def.collideConnected=options.self_collide}else if(options.type=="wheel"){joint_def=new Box2D.Dynamics.Joints.b2LineJointDef;joint_def.Initialize(body_a,body_b,lpa,options.axis);joint_def.collideConnected=options.self_collide;if(options.limit_joint){joint_def.enableLimit=
    true;joint_def.lowerTranslation=options.lower_limit/ws;joint_def.upperTranslation=options.upper_limit/ws}if(options.motor_enabled){joint_def.enableMotor=true;joint_def.motorSpeed=options.motor_speed;joint_def.maxMotorForce=options.max_motor_force}}else if(options.type=="mouse"){joint_def=new Box2D.Dynamics.Joints.b2MouseJointDef;joint_def.collideConnected=options.self_collide;joint_def.bodyA=body_a;joint_def.bodyB=body_b;joint_def.collideConnected=options.self_collide;joint_def.maxForce=options.max_motor_force;
    joint_def.dampingRatio=options.damping}var joint=world.CreateJoint(joint_def);this.joints.push(joint);return joint};Actor.prototype.removeJoint=function(joint){var joints=this.joints;var count=joints.length;for(var t=0;t<count;t++)if(joints[t]==joint){world.DestroyJoint(joint);joints.splice(t,1);return}};
Actor.prototype.updateTransform=function(){var trans=this.transform;if(this.transform_dirty){var scene=this.scene;var r=this.rotation;var sx=this.scale_x;var sy=this.scale_y;var parent=this.parent;if(parent==null||this.orphaned){this.accum_scale_x=sx;this.accum_scale_y=sy}else{this.accum_scale_x=sx*parent.accum_scale_x;this.accum_scale_y=sy*parent.accum_scale_y}var cos=Math.cos(r);var sin=Math.sin(r);if(this.depth!=0&&this.depth!=1){var ooa=1/this.depth;sx*=ooa;sy*=ooa;trans[4]=(this.x-scene.camera_x)*
    ooa;trans[5]=(this.y-scene.camera_y)*ooa}else{trans[4]=this.x;trans[5]=this.y}trans[0]=cos*sx;trans[1]=sin*sx;trans[2]=-sin*sy;trans[3]=cos*sy;var ox=this.ox;var oy=this.oy;if(ox!=0||oy!=0){if(!this.absolute_origin){ox*=this.w;oy*=this.h}var pre_mat=[1,0,0,1,-ox,-oy];Maths.preMulMatrix(trans,pre_mat)}this.transform_dirty=false}if(parent!=null&&!this.orphaned)Maths.mulMatrix(trans,parent.transform)};
Actor.prototype.draw=function(){if(!this.visible)return;if(this.cache){this.drawToCache();this.cache=false}var cache=this.cache_canvas;var scene=this.scene;var app=scene.app;var dscale=app.canvas_scale;var disp=app.display;var context=disp.context;this.preDraw(context);if(cache===null){var src=null;var atlas=this.atlas;if(atlas!=null)if(this.anim_frames!=null)src=atlas.getFrame(this.anim_frames[this.current_frame<<0]);else src=atlas.getFrame(this.current_frame<<0)}var mx=app.canvas_cx+this.scene.x*
    dscale;var my=app.canvas_cy+this.scene.y*dscale;var cx=this.w/2;var cy=this.h/2;cx=cx+.5<<0;cy=cy+.5<<0;if(!this.ignore_camera&&(this.depth==0||this.depth==1)){mx-=scene.camera_x*dscale;my-=scene.camera_y*dscale}this.updateTransform();var trans=this.transform;var self_clip=this.self_clip;var clip_children=this.clip_children;context.setTransform(trans[0]*dscale,trans[1]*dscale,trans[2]*dscale,trans[3]*dscale,trans[4]*dscale+mx,trans[5]*dscale+my);if(self_clip)this.setClipping(context,-cx,-cy);if(cache===
    null)if(atlas!=null)context.drawImage(atlas.bitmap.image,src.x,src.y,src.w,src.h,-cx,-cy,this.w,this.h);else{if(this.bitmap!=null)context.drawImage(this.bitmap.image,-cx,-cy,this.w,this.h)}else context.drawImage(cache,-cache.width>>1,-cache.height>>1);this.postDraw(context);if(clip_children){if(!self_clip)this.setClipping(context,-cx,-cy)}else if(self_clip)context.restore();var count=this.actors.length;if(count>0){var acts=this.actors;for(var t=0;t<count;t++)acts[t].draw()}if(clip_children)context.restore()};
Actor.prototype.drawToCache=function(){var cache=document.createElement("canvas");cache.width=this.w;cache.height=this.h;var context=cache.getContext("2d");var src=null;var atlas=this.atlas;if(atlas!=null)if(this.anim_frames!=null)src=atlas.getFrame(this.anim_frames[this.current_frame<<0]);else src=atlas.getFrame(this.current_frame<<0);if(atlas!=null)context.drawImage(atlas.bitmap.image,src.x,src.y,src.w,src.h,0,0,this.w,this.h);else if(this.bitmap!=null)context.drawImage(this.bitmap.image,0,0,this.w,
    this.h);this.cache_canvas=cache};Actor.prototype.preDraw=function(context){if(this.parent==null||!this.use_parent_opacity)this.accum_opacity=this.opacity*this.scene.opacity;else this.accum_opacity=this.parent.accum_opacity*this.opacity;context.globalAlpha=this.accum_opacity;if(this.shadow){context.shadowOffsetX=this.shadow_x;context.shadowOffsetY=this.shadow_y;context.shadowColor=this.shadow_colour;context.shadowBlur=this.shadow_blur}if(this.composite_op!=null)context.globalCompositeOperation=this.composite_op};
Actor.prototype.postDraw=function(context){if(this.shadow)context.shadowColor="transparent";if(this.composite_op!=null)context.globalCompositeOperation="source-over"};
Actor.prototype.baseUpdate=function(dt){if(!this.active)return false;if(this.onTick!==undefined)this.onTick(dt);if(this.virtual)this.Virtual_update(dt);var scene=this.scene;if(this.atlas!=null){this.current_frame+=this.frame_speed*dt;var max;if(this.anim_frames!=null)max=this.anim_frames.length;else max=this.atlas.getMaxFrames();if(this.current_frame>max)this.current_frame-=max}if(this.body!=null){var pos=this.body.GetPosition();var ws=scene.world_scale;this.setRotation(this.body.GetAngle());this.setPosition(pos.x*
    ws,pos.y*ws)}else{this.rotation+=this.vr*dt;this.vr*=this.vr_damping;this.x+=this.vx*dt;this.vx*=this.vx_damping;this.y+=this.vy*dt;this.vy*=this.vy_damping;this.transform_dirty=true}if(this.vd!=0){this.depth+=this.vd*dt;this.vd*=this.vd_damping}if(this.wrap_position){var left=scene.extents[0];var right=left+scene.extents[2];var top=scene.extents[1];var bottom=top+scene.extents[3];if(this.x<left)this.x=right;else if(this.x>right)this.x=left;if(this.y<top)this.y=bottom;else if(this.y>bottom)this.y=
    top}if(this.parent==null||!this.parent.virtual){if(this.dock_x!=0)if(this.dock_x==Actor.Dock_Left)this.x=-scene.w/2+this.w*this.scale_x/2+this.margin[0];else if(this.dock_x==Actor.Dock_Right)this.x=scene.w/2-this.w*this.scale_x/2-this.margin[1];if(this.dock_y!=0)if(this.dock_y==Actor.Dock_Top)this.y=-scene.h/2+this.h*this.scale_y/2+this.margin[2];else if(this.dock_y==Actor.Dock_Bottom)this.y=scene.h/2-this.h*this.scale_y/2-this.margin[3]}var count=this.actors.length;if(count>0){var acts=this.actors;
    for(var t=0;t<count;t++)acts[t].update(dt)}this.cleanupDestroyedActors();if(this.order_changed){this.order_changed=false;Utils.sortLayers(this.actors)}this.frame_count++};Actor.prototype.update=function(dt){return this.baseUpdate(dt)};Actor.prototype.updateToPhysics=function(){if(this.body==null)return;var b2Vec2=Box2D.Common.Math.b2Vec2;this.body.SetLinearVelocity(new b2Vec2(this.vx,this.vy));this.body.SetAngularVelocity(this.vr);this.body.SetAwake(true)};
Actor.prototype.dirty=function(){this.transform_dirty=true;var a=this.actors;var count=a.length;for(var t=0;t<count;t++)a[t].dirty()};Actor.prototype.makeVirtual=function(){this.prev_scroll_pos_x=0;this.prev_scroll_pos_y=0;this.scroll_pos_x=0;this.scroll_pos_y=0;this.scroll_vx=0;this.scroll_vy=0;this.scroll_range=[0,0,0,0];this.virtual=true};
Actor.prototype.Virtual_onMoveTouch=function(touch_pos){if(this.touching&&(this.scroll_range[2]!=0||this.scroll_range[3]!=0)){var app=this.scene.app;this.prev_scroll_pos_x=this.scroll_pos_x;this.prev_scroll_pos_y=this.scroll_pos_y;this.scroll_vx=app.touch_drag_x;this.scroll_pos_x+=app.touch_drag_x;this.scroll_vy=app.touch_drag_y;this.scroll_pos_y+=app.touch_drag_y;if(this.scroll_vx!=0||this.scroll_vy!=0){this.Virtual_scrollRangeCheck();this.Virtual_updateLayout()}}};
Actor.prototype.Virtual_update=function(dt){var layout_dirty=false;if(!this.touching){this.prev_scroll_pos_x=this.scroll_pos_x;this.prev_scroll_pos_y=this.scroll_pos_y;this.scroll_pos_x+=this.scroll_vx;this.scroll_pos_y+=this.scroll_vy;if(this.scroll_vx!=0||this.scroll_vy!=0){this.Virtual_scrollRangeCheck();this.Virtual_updateLayout()}this.scroll_vx*=.9;this.scroll_vy*=.9;if(this.scroll_vx>-.5&&this.scroll_vx<.5)this.scroll_vx=0;if(this.scroll_vy>-.5&&this.scroll_vy<.5)this.scroll_vy=0}if(this.frame_count==
    0)this.Virtual_updateLayout()};Actor.prototype.Virtual_scrollRangeCheck=function(){var x=this.scroll_pos_x;var y=this.scroll_pos_y;var left=-this.scroll_range[0];var right=left-this.scroll_range[2];var top=-this.scroll_range[1];var bottom=top-this.scroll_range[3];if(x<right){x=right;this.scroll_vx=0}else if(x>left){x=left;this.scroll_vx=0}if(y<bottom){y=bottom;this.scroll_vy=0}else if(y>top){y=top;this.scroll_vy=0}this.scroll_pos_x=x;this.scroll_pos_y=y};
Actor.prototype.Virtual_updateLayout=function(dt){var dx=this.prev_scroll_pos_x-this.scroll_pos_x;var dy=this.prev_scroll_pos_y-this.scroll_pos_y;var count=this.actors.length;var w=this.w*this.scale_x/2;var h=this.h*this.scale_y/2;if(count>0){var act;var acts=this.actors;for(var t=0;t<count;t++){act=acts[t];if(act.dock_x!=0)if(act.dock_x==Actor.Dock_Left)act.x=-w+act.w*act.scale_x/2+act.margin[0];else{if(act.dock_x==Actor.Dock_Right)act.x=w-act.w*act.scale_x/2-act.margin[1]}else act.x+=dx;if(act.dock_y!=
    0)if(act.dock_y==Actor.Dock_Top)act.y=-h+act.h*act.scale_y/2+act.margin[2];else{if(act.dock_y==Actor.Dock_Bottom)act.y=h-act.h*act.scale_y/2-act.margin[3]}else act.y+=dy;act.transform_dirty=true}}};
Actor.prototype.hitTest=function(position){if(!this.touchable)return null;var count=this.actors.length;var act;if(count>0){var acts=this.actors;for(var t=0;t<count;t++){act=acts[t].hitTest(position);if(act!=null)return act}}var scene=this.scene;var trans=this.transform;var cx=trans[4]+scene.x;var cy=trans[5]+scene.y;if(!this.ignore_camera){cx-=scene.camera_x;cy-=scene.camera_y}var sx=this.accum_scale_x;var sy=this.accum_scale_y;var px=(position.x-cx)/sx;var py=(position.y-cy)/sy;var tx=px*trans[0]+
    py*trans[1];var ty=px*trans[2]+py*trans[3];var hw=this.w*sx/2;var hh=this.h*sy/2;if(tx>=-hw&&tx<=hw&&ty>=-hh&&ty<=hh)return this;return null};Actor.prototype.transformPoint=function(x,y){return Maths.vecMulMatrix(x,y,this.transform)};
Actor.prototype.setClipping=function(context,x,y){context.save();context.beginPath();var clip_margin=this.clip_margin;var shape=this.clip_shape;if(shape==null){var type=this.type;if(type==Actor.Type_Arc)context.arc(0,0,this.radius,0,2*Math.PI);else if(type==Actor.Type_Polygon){context.beginPath();var points=this.points;var count=points.length;context.moveTo(points[0],points[1]);for(var i=2;i<count;i+=2)context.lineTo(points[i],points[i+1]);context.closePath()}else context.rect(x+clip_margin[0],y+
    clip_margin[1],this.w-clip_margin[2]-clip_margin[0],this.h-clip_margin[3]-clip_margin[1])}else{var type=shape.type;if(type==Shape.TypeBox)context.rect(x+clip_margin[0],y+clip_margin[1],shape.width-clip_margin[2]-clip_margin[0],shape.height-clip_margin[3]-clip_margin[1]);else if(type==Shape.TypeCircle)context.arc(0,0,shape.width,0,2*Math.PI,false);else if(type==Shape.TypePolygon){var points=shape.vertices;var count=points.length;context.moveTo(points[0],points[1]);for(var i=2;i<count;i+=2)context.lineTo(points[i],
    points[i+1]);context.closePath()}}context.clip()};Actor.prototype.overlaps=function(other){var w1=this.w;var h1=this.h;var w2=other.w;var h2=other.h;var x1=this.x-w1/2;var y1=this.y-h1/2;var x2=other.x-w2/2;var y2=other.y-h2/2;return!(y1+h1<y2||y1>y2+h2||x1>x2+w2||x1+w1<x2)};function Ease(){}Ease.linear=0;Ease.quadin=1;Ease.quadout=2;Ease.cubicin=3;Ease.cubicout=4;Ease.quartin=5;Ease.quartout=6;Ease.sin=7;Ease.easingFuncs=[function(d){return d},function(d){return d*d},function(d){return d*(2-d)},function(d){return d*d*d},function(d){d-=1;return d*d*d+1},function(d){return d*d*d*d},function(d){d-=1;return-(d*d*d*d-1)},function(d){return Math.sin(d*Math.PI/2)}];
function Animation(timeline,target,property,frames,times,repeat,easing){this.timeline=timeline;this.state=Animation.AS_playing;this.time=-1E-6;this.repeats_left=repeat;this.index=-1;this.target=target;this.property=property;this.frames=frames;this.times=times;this.easing=easing;this.repeat=repeat;this.destroy=true;this.actions=[];this.time_scale=1}Animation.AS_playing=0;Animation.AS_paused=1;Animation.prototype.pause=function(){this.state=Animation.AS_paused};
Animation.prototype.play=function(){this.state=Animation.AS_playing};Animation.prototype.restart=function(){this.state=Animation.AS_playing;this.time=-1E-6;this.index=-1;this.repeats_left=this.repeat};
Animation.prototype.update=function(dt){if(this.state!=Animation.AS_playing)return;dt*=this.time_scale;var time=this.time+dt;var times=this.times;var frames=this.frames;var count=times.length;var start=this.index;for(var t=start;t<count;t++){var t1=times[t];if(time<t1){this.index=t;if(time>=times[0]){if(this.index!=start){var action=this.actions[this.index-1];if(action!==undefined)action()}var t2=times[t-1];var fstart=frames[t-1];var dtime=t1-t2;var dframe=frames[t]-fstart;var ddt=time-t2;if(ddt!=
    0)if(this.easing!==undefined)this.target[this.property]=fstart+dframe*Ease.easingFuncs[this.easing[t-1]](ddt/dtime);else this.target[this.property]=fstart+dframe*ddt/dtime}break}}var duration=times[times.length-1];if(time>duration){if(this.repeat>0)this.repeats_left--;if(this.repeat==0||this.repeats_left>0){time-=duration;if(this.onRepeat!==undefined)this.onRepeat(this);this.target[this.property]=frames[0]}else{this.target[this.property]=frames[times.length-1];this.state=Animation.AS_paused;if(this.onEnd!==
    undefined)this.onEnd(this);if(this.destroy)this.timeline.remove(this)}this.index=-1}this.time=time};Animation.prototype.setTime=function(time){this.time=time;this.index=-1;this.update(0)};Animation.prototype.setAction=function(index,action_function){this.actions[index]=action_function};function Timeline(target,property,frames,times,repeat,easing){this.anims=[];this.manager=null;this.name="";if(target!==undefined)this.add(target,property,frames,times,repeat,easing)}
Timeline.prototype.add=function(target,property,frames,times,repeat,easing){var anim=new Animation(this,target,property,frames,times,repeat,easing);this.anims.push(anim);return anim};Timeline.prototype.remove=function(animation){var anims=this.anims;var count=anims.length;for(var t=0;t<count;t++)if(anims[t]==animation){anims.splice(t,1);return}};Timeline.prototype.pause=function(){var count=this.anims.length;for(var t=0;t<count;t++)this.anims[t].pause()};
Timeline.prototype.play=function(){var count=this.anims.length;for(var t=0;t<count;t++)this.anims[t].play()};Timeline.prototype.restart=function(){var count=this.anims.length;for(var t=0;t<count;t++)this.anims[t].restart()};Timeline.prototype.print=function(){var count=this.anims.length;for(var t=0;t<count;t++)console.log(this.anims[t])};Timeline.prototype.update=function(dt){var count=this.anims.length;if(count==0&&this.manager!==undefined){this.manager.remove(this);return}for(var t=count-1;t>=0;t--)this.anims[t].update(dt)};
function TimelineManager(){this.timelines=[]}TimelineManager.prototype.add=function(timeline){this.timelines.push(timeline);timeline.manager=this;return timeline};TimelineManager.prototype.remove=function(timeline){var timelines=this.timelines;var count=timelines.length;for(var t=0;t<count;t++)if(timelines[t]==timeline){timelines.splice(t,1);return}};TimelineManager.prototype.pause=function(){var count=this.timelines.length;for(var t=0;t<count;t++)this.timelines[t].pause()};
TimelineManager.prototype.play=function(){var count=this.timelines.length;for(var t=0;t<count;t++)this.timelines[t].play()};TimelineManager.prototype.restart=function(){var count=this.timelines.length;for(var t=0;t<count;t++)this.timelines[t].restart()};TimelineManager.prototype.print=function(){var count=this.timelines.length;for(var t=0;t<count;t++)console.log(this.timelines[t])};TimelineManager.prototype.update=function(dt){var count=this.timelines.length;for(var t=count-1;t>=0;t--)this.timelines[t].update(dt)};function TheApp(canvas){this.touched=false;this.touch_pos={x:0,y:0};this.touch_drag_x=0;this.touch_drag_y=0;this.last_time=Date.now();this.dt=0;this.avg_time=0;this.avg_fps=60;this.avg_frame=0;this.canvas_scale=1;this.canvas_cx=this.canvas_width/2;this.canvas_cy=this.canvas_height/2;this.order_changed=true;this.scenes=[];this.removals=[];this.canvas=canvas;this.pixel_ratio=1;this.canvas_width=canvas.width;this.canvas_height=canvas.height;this.display_width=canvas.width;this.display_height=canvas.height;
    this.canvas_scale_method=TheApp.FitNone;this.touch_supported=this.isTouchSupported();this.allow_touchables=true;this.target_frame_rate=60;this.adaptive_physics=false;this.focus_scene=null;this.clear_canvas=false;this.touch_focus=null;this.debug=false;this.use_marm=false;this.timelines=new TimelineManager;this.box2d=typeof Box2D!="undefined";this.bitmaps=[];this.brushes=[];this.shapes=[];this.materials=[];this.sounds=[];if(window.devicePixelRatio!==undefined)this.pixel_ratio=window.devicePixelRatio;
    this.display=new Display(this.canvas);if(this.touch_supported){canvas.addEventListener("touchstart",this.onTouchStart,false);canvas.addEventListener("touchmove",this.onTouchMove,false);canvas.addEventListener("touchend",this.onTouchEnd,false)}else{canvas.addEventListener("mousedown",this.onTouchStart,false);canvas.addEventListener("mousemove",this.onTouchMove,false);canvas.addEventListener("mouseup",this.onTouchEnd,false);canvas.addEventListener("mouseout",this.onTouchEnd,false)}window.addEventListener("keypress",
        this.onKeyPress,false);window.addEventListener("keydown",this.onKeyDown,false);window.addEventListener("keyup",this.onKeyUp,false);this.resize=function(event){window.app.setCanvasScalingMethod()};this.orientationChange=function(event){};window.addEventListener("resize",this.resize)}TheApp.version=1.4;TheApp.FitNone=0;TheApp.FitX=1;TheApp.FitY=2;TheApp.FitBest=3;TheApp.FitSize=4;TheApp.prototype.onKeyPress=function(e){var app=window.app;if(app.focus_scene!=null)app.focus_scene.onKeyPressBase(e)};
TheApp.prototype.onKeyDown=function(e){var app=window.app;if(app.focus_scene!=null)app.focus_scene.onKeyDownBase(e)};TheApp.prototype.onKeyUp=function(e){var app=window.app;if(app.focus_scene!=null)app.focus_scene.onKeyUpBase(e)};TheApp.prototype.isTouchSupported=function(){var msTouchEnabled=window.navigator.msMaxTouchPoints;var generalTouchEnabled="ontouchstart"in this.canvas;if(msTouchEnabled||generalTouchEnabled)return true;return false};
TheApp.prototype.onTouchStart=function(e){var app=window.app;if(app.touch_supported){e.stopPropagation();e.preventDefault()}var display=app.display;app.touched=true;if(app.touch_supported)app.touch_pos=display.getCanvasPoint(e.changedTouches[0].pageX,e.changedTouches[0].pageY);else app.touch_pos=display.getCanvasPoint(e.pageX,e.pageY);if(app.focus_scene!=null)app.focus_scene.onBeginTouchBase(app.touch_pos);if(app.allow_touchables){var actor=app.findHitActor(app.touch_pos);if(actor!=null){app.touch_focus=
    actor;actor.onBeginTouchBase(app.touch_pos)}}};
TheApp.prototype.onTouchEnd=function(e){var app=window.app;if(app.touch_supported){e.stopPropagation();e.preventDefault()}var display=app.display;app.touched=false;if(app.touch_supported)app.touch_pos=display.getCanvasPoint(e.changedTouches[0].pageX,e.changedTouches[0].pageY);else app.touch_pos=display.getCanvasPoint(e.pageX,e.pageY);if(app.focus_scene!=null)app.focus_scene.onEndTouchBase(app.touch_pos);if(app.allow_touchables){var actor=app.findHitActor(app.touch_pos);if(actor!=null)actor.onEndTouchBase(app.touch_pos);
    if(app.touch_focus!=null){if(app.touch_focus.onLostTouchFocus!==undefined)app.touch_focus.onLostTouchFocus(app.touch_pos);app.touch_focus=null}}};
TheApp.prototype.onTouchMove=function(e){var app=window.app;if(app.touch_supported){e.stopPropagation();e.preventDefault()}var old_x=app.touch_pos.x;var old_y=app.touch_pos.y;var display=app.display;if(app.touch_supported)app.touch_pos=display.getCanvasPoint(e.changedTouches[0].pageX,e.changedTouches[0].pageY);else app.touch_pos=display.getCanvasPoint(e.pageX,e.pageY);app.touch_drag_x=old_x-app.touch_pos.x;app.touch_drag_y=old_y-app.touch_pos.y;if(app.focus_scene!=null)app.focus_scene.onMoveTouchBase(app.touch_pos);
    if(app.allow_touchables){var actor=app.findHitActor(app.touch_pos);if(actor!=null)actor.onMoveTouchBase(app.touch_pos)}};TheApp.prototype.addScene=function(scene){this.scenes.push(scene);scene.app=this;return scene};TheApp.prototype.removeScene=function(scene){if(this.focus_scene==scene)this.focus_scene=null;this.removals.push(scene)};
TheApp.prototype.cleanupDestroyedScenes=function(){var dcount=this.removals.length;if(dcount>0){var removals=this.removals;var scenes=this.scenes;var count=scenes.length;for(var s=0;s<dcount;s++){var dscene=removals[s];for(var t=0;t<count;t++)if(dscene==scenes[t]){dscene.release();scenes.splice(t,1);count--;break}}}this.removals=[]};TheApp.prototype.findScene=function(name){var scenes=this.scenes;var count=scenes.length;for(var t=0;t<count;t++)if(scenes[t].name==name)return scenes[t];return null};
TheApp.prototype.getResFromType=function(type){if(type=="brush")return this.brushes;else if(type=="sound")return this.sounds;else if(type=="shape")return this.shapes;else if(type=="material")return this.materials;else if(type=="bitmap")return this.bitmaps;return null};TheApp.prototype.addResource=function(resource,type){var res=this.getResFromType(type);if(res!=null){res.push(resource);res.parent=this}};
TheApp.prototype.removeResource=function(resource,type){var res=this.getResFromType(type);if(res!=null){var count=res.length;for(var t=0;t<count;t++)if(res[t].name==name){res.splice(t,1);return}}};TheApp.prototype.findResource=function(name,type){var res=this.getResFromType(type);if(res==null)return null;var count=res.length;for(var t=0;t<count;t++)if(res[t].name==name)return res[t];if(this.debug)console.log("resource '"+name+"' ("+type+") not found");return null};
TheApp.prototype.areResourcesLoaded=function(include_scenes){var res=this.bitmaps;var count=res.length;for(var t=0;t<count;t++)if(!res[t].loaded)return false;if(include_scenes){var scenes=this.scenes;count=scenes.length;for(t=0;t<count;t++)if(!scenes[t].areResourcesLoaded())return false}return true};TheApp.prototype.draw=function(){var scenes=this.scenes;var count=scenes.length;for(var t=0;t<count;t++)scenes[t].draw()};
TheApp.prototype.update=function(dt){var app=window.app;var scenes=this.scenes;var count=scenes.length;app.dt=dt;app.timelines.update(dt);for(var t=0;t<count;t++)scenes[t].update(dt);this.cleanupDestroyedScenes();if(this.order_changed){this.order_changed=false;Utils.sortLayers(this.scenes)}};
TheApp.prototype.mainLoop=function(){var app=window.app;var now=Date.now();var delta=now-app.last_time;app.last_time=now;if(app.clear_canvas)app.display.clear(true);app.update(delta/1E3);app.draw();app.avg_time+=delta;app.avg_frame++;if(app.avg_frame==60){app.avg_frame=0;app.avg_fps=6E4/app.avg_time;app.avg_time=0}requestAnimationFrame(app.mainLoop)};TheApp.prototype.start=function(){this.mainLoop()};
TheApp.prototype.findHitActor=function(position){if(this.focus_scene!=null)return this.focus_scene.findHitActor(position);return null};TheApp.prototype.dirty=function(){var s=this.scenes;var count=s.length;for(var t=0;t<count;t++)s[t].dirty()};
TheApp.prototype.setCanvasScalingMethod=function(method){if(method!==undefined)this.canvas_scale_method=method;var method=this.canvas_scale_method;var dw=window.innerWidth;var dh=window.innerHeight;if(this.canvas_scale_method==TheApp.FitNone);else if(this.canvas_scale_method==TheApp.FitSize){this.canvas_scale=1;this.canvas.width=dw;this.canvas.height=dh;this.display_width=dw;this.display_height=dh;this.canvas_cx=dw/2;this.canvas_cy=dh/2;this.dirty()}else{this.scaleCanvasToFit=true;var sw=this.canvas_width;
    var sh=this.canvas_height;var sx=dw/sw;var sy=dh/sh;var scale=1;switch(this.canvas_scale_method){case TheApp.FitX:scale=sx;break;case TheApp.FitY:scale=sy;break;case TheApp.FitBest:scale=sx<sy?sx:sy;break}this.canvas_scale=scale;this.display_width=dw;this.display_height=dh;this.canvas.width=dw*this.pixel_ratio;this.canvas.height=dh*this.pixel_ratio;this.canvas_cx=dw/2;this.canvas_cy=dh/2;this.dirty()}};
TheApp.prototype.parseAndSetFocus=function(scene_name){var app=window.app;(new Xoml(app)).parseResources(app,[window[scene_name]]);app.order_changed=true;app.focus_scene=app.findScene(scene_name)};ArcActor.prototype=new Actor;ArcActor.prototype.constructor=ArcActor;ArcActor.prototype.parent=Actor.prototype;function ArcActor(){this.fill_style="#ffffff";this.stroke_style="#ffffff";this.stroke_thickness=1;this.radius=1;this.start_angle=0;this.end_angle=2*Math.PI;this.filled=true;this.grad_rotation=0;Actor.call(this);this.type=Actor.Type_Arc}ArcActor.prototype.update=function(dt){return this.baseUpdate(dt)};
ArcActor.prototype.draw=function(){if(!this.visible)return;if(this.cache){this.drawToCache();this.cache=false}var cache=this.cache_canvas;var scene=this.scene;var app=scene.app;var dscale=app.canvas_scale;var context=app.display.context;if(cache===null){if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;if(!this.filled&&this.stroke_style!="")context.strokeStyle=this.stroke_style;if(!this.filled)context.lineWidth=this.stroke_thickness}this.preDraw(context);var mx=app.canvas_cx+scene.x*
    dscale;var my=app.canvas_cy+scene.y*dscale;if(!this.ignore_camera&&(this.depth==0||this.depth==1)){mx-=scene.camera_x*dscale;my-=scene.camera_y*dscale}this.updateTransform();var trans=this.transform;var self_clip=this.self_clip;var clip_children=this.clip_children;context.setTransform(trans[0]*dscale,trans[1]*dscale,trans[2]*dscale,trans[3]*dscale,trans[4]*dscale+mx,trans[5]*dscale+my);if(self_clip)this.setClipping(context,0,0);if(cache===null)app.display.drawArc(0,0,this.radius,this.start_angle,
    this.end_angle,this.filled);else context.drawImage(cache,-cache.width>>1,-cache.height>>1);this.postDraw(context);if(clip_children){if(!self_clip)this.setClipping(context,0,0)}else if(self_clip)context.restore();var count=this.actors.length;if(count>0){var acts=this.actors;for(var t=0;t<count;t++)acts[t].draw()}if(clip_children)context.restore()};
ArcActor.prototype.drawToCache=function(){var cache=document.createElement("canvas");var w=this.w;var h=this.h;var ox=0;var oy=0;if(!this.filled&&this.stroke_style!=""){w+=this.stroke_thickness;h+=this.stroke_thickness;ox=this.stroke_thickness/2+.5<<0;oy=this.stroke_thickness/2+.5<<0}cache.width=w;cache.height=h;var scene=this.scene;var app=scene.app;var context=cache.getContext("2d");if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;if(!this.filled&&this.stroke_style!="")context.strokeStyle=
    this.stroke_style;if(!this.filled)context.lineWidth=this.stroke_thickness;context.setTransform(1,0,0,1,this.w/2,this.h/2);app.display.drawArc(ox,oy,this.radius,this.start_angle,this.end_angle,this.filled,context);this.cache_canvas=cache};
ArcActor.prototype.hitTest=function(position){if(!this.touchable)return null;var count=this.actors.length;var act;if(count>0){var acts=this.actors;for(var t=0;t<count;t++){act=acts[t].hitTest(position);if(act!=null)return act}}var scene=this.scene;var trans=this.transform;var cx=trans[4]+scene.x;var cy=trans[5]+scene.y;if(!this.ignore_camera){cx-=scene.camera_x;cy-=scene.camera_y}var sx=this.accum_scale_x;var sy=this.accum_scale_y;var px=(position.x-cx)/sx;var py=(position.y-cy)/sy;var tx=px*trans[0]+
    py*trans[1];var ty=px*trans[2]+py*trans[3];var r=this.radius*sx;r*=r;var d=tx*tx+ty*ty;if(d<=r)return this;return null};function Bitmap(name,location,preload,onload){this.image=new Image;this.parent=null;this.name=name;this.location=location;this.onload=onload;this.loaded=false;if(preload){var that=this;this.image.onload=function(){that.loaded=true;if(onload!==undefined)onload()};this.image.src=location}}Bitmap.prototype.load=function(){var that=this;this.image.onload=function(){that.loaded=true;if(that.onload!==undefined)that.onload()};this.image.src=this.location};
Bitmap.prototype.destroy=function(){this.image=null;if(this.parent!=null)this.parent.removeResource(this,"bitmap")};function Display(canvas){this.canvas=canvas;this.context=canvas.getContext("2d");this.context.lineWidth=1;this.context.strokeStyle="black";this.context.fillStyle="black";this.context.globalAlpha=1;this.context.lineJoin="round";this.context.lineCap="round"}Display.prototype.getCanvasPoint=function(x_pos,y_pos){var app=window.app;var scale=app.canvas_scale;return{x:(x_pos-this.canvas.offsetLeft-app.canvas_cx)/scale,y:(y_pos-this.canvas.offsetTop-app.canvas_cy)/scale}};
Display.prototype.clear=function(transparent){var app=window.app;var ctx=this.context;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,app.display_width,app.display_height)};Display.prototype.drawPolygon=function(x,y,points,fill,context){var ctx=this.context;if(context!==undefined)ctx=context;var count=points.length;ctx.beginPath();ctx.moveTo(points[0]+x,points[1]+y);for(var i=2;i<count;i+=2)ctx.lineTo(points[i]+x,points[i+1]+y);if(fill)ctx.fill();else{ctx.lineTo(points[0]+x,points[1]+y);ctx.stroke()}return this};
Display.prototype.drawLine=function(x1,y1,x2,y2,context){var ctx=this.context;if(context!==undefined)ctx=context;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();return this};Display.prototype.drawRect=function(x,y,w,h,fill,context){var ctx=this.context;if(context!==undefined)ctx=context;if(fill)ctx.fillRect(x,y,w,h);else ctx.strokeRect(x,y,w,h);return this};
Display.prototype.drawRoundRect=function(x,y,w,h,radius,fill,context){var ctx=this.context;if(context!==undefined)ctx=context;ctx.beginPath();ctx.moveTo(x+radius,y);ctx.lineTo(x+w-radius,y);ctx.quadraticCurveTo(x+w,y,x+w,y+radius);ctx.lineTo(x+w,y+h-radius);ctx.quadraticCurveTo(x+w,y+h,x+w-radius,y+h);ctx.lineTo(x+radius,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-radius);ctx.lineTo(x,y+radius);ctx.quadraticCurveTo(x,y,x+radius,y);ctx.closePath();if(fill)ctx.fill();else ctx.stroke()};
Display.prototype.drawArc=function(x,y,radius,start_angle,end_angle,fill,context){var ctx=this.context;if(context!==undefined)ctx=context;ctx.beginPath();ctx.arc(x,y,radius,start_angle,end_angle);if(fill)ctx.fill();else ctx.stroke();return this};Display.prototype.drawAtlasImage=function(image,src_x,src_y,src_w,src_h,x,y,w,h){this.context.drawImage(image,src_x,src_y,src_w,src_h,x,y,w,h)};Display.prototype.drawImage=function(image,x,y,w,h){this.context.drawImage(image,x,y,w,h)};function Geometry(name,vertices){this.name=name;this.vertices=[];if(vertices!=undefined)this.vertices=vertices};function ImageAtlas(name,bitmap,x,y,w,h){this.frames=[];this.parent=null;this.name=name;this.bitmap=bitmap;if(x!==undefined&&y!==undefined&&w!==undefined&&h!==undefined)this.addFrame(x,y,w,h)}ImageAtlas.prototype.addFrame=function(sx,sy,sw,sh){this.frames.push({x:sx,y:sy,w:sw,h:sh})};ImageAtlas.prototype.getFrame=function(index){return this.frames[index]};ImageAtlas.prototype.getMaxFrames=function(){return this.frames.length};
ImageAtlas.prototype.generate=function(start_x,start_y,frame_w,frame_h,count_x,count_y,total){if(total!==undefined)total=count_x*count_y;var fy=start_y;for(var y=0;y<count_y;y++){var fx=start_x;for(var x=0;x<count_x;x++){this.addFrame(fx,fy,frame_w,frame_h);fx+=frame_w;total--;if(total<=0)return}fy+=frame_h}};ImageAtlas.prototype.destroy=function(){if(this.parent!=null)this.parent.removeResource(this,"brush")};function Gradient(name,colour_stops){this.parent=null;this.name=name;if(colour_stops!==undefined)this.stops=colour_stops;else this.stops=[]}Gradient.prototype.addColourStop=function(colour,offset){this.stops.push({c:colour,offs:offset})};Gradient.prototype.getColourStop=function(index){return this.stops[index]};Gradient.prototype.getMaxStops=function(){return this.stops.length};Gradient.prototype.destroy=function(){if(this.parent!=null)this.parent.removeResource(this,"brush")};
Gradient.prototype.createStyle=function(w,h,start,end){if(this.stops!==undefined){var x1=0,y1=0;var x2=1,y2=0;if(start!==undefined){x1=start.x;y1=start.y}if(end!==undefined){x2=end.x;y2=end.y}x1=x1*w-w/2;y1=y1*h-h/2;x2=x2*w-w/2;y2=y2*h-h/2;var grad=window.app.display.context.createLinearGradient(x1,y1,x2,y2);for(var t=0;t<this.stops.length;t++){var s=this.stops[t];grad.addColorStop(s.offs,s.c)}return grad}return null};LabelActor.prototype=new Actor;LabelActor.prototype.constructor=LabelActor;LabelActor.prototype.parent=Actor.prototype;function LabelActor(){this.text="";this.font="16pt Calibri";this.text_align="center";this.text_baseline="middle";this.fill_style="#ffffff";this.stroke_style="#ffffff";this.stroke_thickness=1;this.filled=true;Actor.call(this);this.type=Actor.Type_Label}LabelActor.prototype.update=function(dt){return this.baseUpdate(dt)};
LabelActor.prototype.draw=function(){if(!this.visible||this.text=="")return;if(this.cache){this.drawToCache();this.cache=false}var cache=this.cache_canvas;var scene=this.scene;var app=scene.app;var dscale=app.canvas_scale;var context=app.display.context;if(cache===null){if(this.font!="")context.font=this.font;if(this.textAlign!="")context.textAlign=this.text_align;if(this.textBaseline!="")context.textBaseline=this.text_baseline;if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;
    if(!this.filled&&this.stroke_style!="")context.strokeStyle=this.stroke_style;if(!this.filled)context.lineWidth=this.stroke_thickness}this.preDraw(context);var mx=app.canvas_cx+scene.x*dscale;var my=app.canvas_cy+scene.y*dscale;if(!this.ignore_camera&&(this.depth==0||this.depth==1)){mx-=scene.camera_x*dscale;my-=scene.camera_y*dscale}this.updateTransform();var trans=this.transform;context.setTransform(trans[0]*dscale,trans[1]*dscale,trans[2]*dscale,trans[3]*dscale,trans[4]*dscale+mx,trans[5]*dscale+
    my);if(cache===null)if(this.filled)context.fillText(this.text,0,0);else context.strokeText(this.text,0,0);else context.drawImage(cache,-cache.width>>1,-cache.height>>1);this.postDraw(context);if(this.shadow)context.shadowColor="transparent";var count=this.actors.length;if(count>0){var acts=this.actors;for(var t=0;t<count;t++)acts[t].draw()}};
LabelActor.prototype.drawToCache=function(){var cache=document.createElement("canvas");cache.width=this.w;cache.height=this.h;var context=cache.getContext("2d");if(this.font!="")context.font=this.font;if(this.textAlign!="")context.textAlign=this.text_align;if(this.textBaseline!="")context.textBaseline=this.text_baseline;if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;if(!this.filled&&this.stroke_style!="")context.strokeStyle=this.stroke_style;if(!this.filled)context.lineWidth=
    this.stroke_thickness;if(this.filled)context.fillText(this.text,this.w/2,this.h/2);else context.strokeText(this.text,this.w/2,this.h/2);this.cache_canvas=cache};function Material(name){this.parent=null;this.name=name;this.type="static";this.density=1;this.friction=.1;this.restitution=.1;this.gravity_scale=1;this.fixed_rotation=false;this.is_bullet=false}Material.prototype.destroy=function(){if(this.parent!=null)this.parent.removeResource(this,"material")};function Maths(){}Maths.mulMatrix=function(mat1,mat2){var m0=mat2[0];var m1=mat2[1];var m2=mat2[2];var m3=mat2[3];var m4=mat2[4];var m5=mat2[5];var n0=mat1[0];var n1=mat1[1];var n2=mat1[2];var n3=mat1[3];var n4=mat1[4];var n5=mat1[5];mat1[0]=m0*n0+m2*n1;mat1[1]=m1*n0+m3*n1;mat1[2]=m0*n2+m2*n3;mat1[3]=m1*n2+m3*n3;mat1[4]=m0*n4+m2*n5+m4;mat1[5]=m1*n4+m3*n5+m5};
Maths.preMulMatrix=function(mat1,mat2){var m0=mat1[0];var m1=mat1[1];var m2=mat1[2];var m3=mat1[3];var m4=mat1[4];var m5=mat1[5];var n0=mat2[0];var n1=mat2[1];var n2=mat2[2];var n3=mat2[3];var n4=mat2[4];var n5=mat2[5];mat1[0]=m0*n0+m2*n1;mat1[1]=m1*n0+m3*n1;mat1[2]=m0*n2+m2*n3;mat1[3]=m1*n2+m3*n3;mat1[4]=m0*n4+m2*n5+m4;mat1[5]=m1*n4+m3*n5+m5};Maths.vecMulMatrix=function(x,y,mat){var tx=x*mat[0]+y*mat[2]+mat[4];var ty=x*mat[1]+y*mat[3]+mat[5];return{x:tx,y:ty}};ParticleActor.prototype=new Actor;ParticleActor.prototype.constructor=ParticleActor;ParticleActor.prototype.parent=Actor.prototype;function ParticleActor(){Actor.call(this);this.type=Actor.Type_Particle;this.gravity=0}
ParticleActor.prototype.resetParticle=function(actor){actor.life_time=0;if(actor.orphaned){var tpos=this.transformPoint(actor.org_x+this.x,actor.org_y+this.y);actor.x=tpos.x;actor.y=tpos.y}else{actor.x=actor.org_x;actor.y=actor.org_y}actor.rotation=actor.org_rotation;actor.scale_x=actor.org_scale_x;actor.scale_y=actor.org_scale_y;actor.depth=actor.org_depth;actor.opacity=actor.org_opacity;actor.current_frame=actor.org_current_frame;actor.vr=actor.org_vr;actor.vx=actor.org_vx;actor.vy=actor.org_vy;
    actor.vd=actor.org_vd;actor.vo=actor.org_vo;actor.vsx=actor.org_vsx;actor.vsy=actor.org_vsy};
ParticleActor.prototype.addParticle=function(actor,life_span,num_lives,spawn_delay){this.addActor(actor);if(actor.vo===undefined)actor.vo=0;if(actor.vsx===undefined)actor.vsx=0;if(actor.vsy===undefined)actor.vsy=0;actor.life_time=-spawn_delay;actor.life_span=life_span;actor.num_lives=num_lives;if(actor.life_time<0){actor.active=false;actor.visible=false}actor.org_num_lives=actor.num_lives;actor.org_x=actor.x;actor.org_y=actor.y;actor.org_rotation=actor.rotation;actor.org_scale_x=actor.scale_x;actor.org_scale_y=
    actor.scale_y;actor.org_depth=actor.depth;actor.org_opacity=actor.opacity;actor.org_current_frame=actor.current_frame;actor.org_vr=actor.vr;actor.org_vx=actor.vx;actor.org_vy=actor.vy;actor.org_vd=actor.vd;actor.org_vo=actor.vo;actor.org_vsx=actor.vsx;actor.org_vsy=actor.vsy;if(actor.orphaned){var tpos=this.transformPoint(actor.org_x+this.x,actor.org_y+this.y);actor.x=tpos.x;actor.y=tpos.y}return actor};
ParticleActor.prototype.update=function(dt){var particles=this.actors;var count=particles.length;if(count==0){if(this.onParticlesEnd!==undefined)this.onParticlesEnd();this.destroy()}else for(var t=count-1;t>=0;t--){var particle=particles[t];particle.life_time+=dt;var life_time=particle.life_time;if(life_time>=0){if(life_time-dt<0&&life_time>=0){particle.active=true;particle.visible=true}if(particle.active){particle.scale_x+=particle.vsx*dt;particle.scale_y+=particle.vsy*dt;particle.opacity+=particle.vo*
    dt;if(particle.opacity<0)particle.opacity=0;particle.vy+=this.gravity*dt;particle.update(dt);if(life_time>=particle.life_span){if(particle.num_lives>0)particle.num_lives--;if(particle.num_lives>0||particle.org_num_lives==0)this.resetParticle(particle);else if(this.onParticleLost!==undefined){if(this.onParticleLost(particle))particle.destroy()}else particle.destroy()}}}}return this.baseUpdate(dt)};
ParticleActor.prototype.generateExplosion=function(count,type,duration,speed,spin_speed,rate,damping,properties){this.updateParentTransforms();for(var t=0;t<count;t++){var particle=new type;for(var prop in properties)particle[prop]=properties[prop];particle.vr+=Math.random()*spin_speed;particle.vx+=Math.random()*speed-speed/2;particle.vy+=Math.random()*speed-speed/2;particle.vx_damping=damping;particle.vy_damping=damping;particle.vo=-1/duration;this.addParticle(particle,duration,1,t/(count*rate))}};
ParticleActor.prototype.generatePlume=function(count,type,duration,speed,spin_speed,rate,damping,properties){this.updateParentTransforms();for(var t=0;t<count;t++){var particle=new type;for(var prop in properties)particle[prop]=properties[prop];particle.vr+=Math.random()*spin_speed;particle.vx+=Math.random()*speed-speed/2;particle.vy+=Math.random()*-speed-speed/2;particle.vx_damping=damping;particle.vy_damping=damping;particle.vo=-1/duration;this.addParticle(particle,duration,0,t/(count*rate))}};
ParticleActor.prototype.generateRain=function(count,type,duration,speed,spin_speed,rate,damping,width,properties){this.updateParentTransforms();for(var t=0;t<count;t++){var particle=new type;for(var prop in properties)particle[prop]=properties[prop];particle.x=Math.random()*width-width/2;particle.vr+=Math.random()*spin_speed;particle.vy+=Math.random()*speed+speed/2;particle.vx_damping=damping;particle.vy_damping=damping;particle.vo=-1/duration;this.addParticle(particle,duration,0,t/(count*rate))}};PolygonActor.prototype=new Actor;PolygonActor.prototype.constructor=PolygonActor;PolygonActor.prototype.parent=Actor.prototype;function PolygonActor(){this.fill_style="#ffffff";this.stroke_style="";this.stroke_thickness=1;this.filled=true;this.points=null;this.grad_rotation=0;Actor.call(this);this.type=Actor.Type_Polygon}PolygonActor.prototype.update=function(dt){return this.baseUpdate(dt)};
PolygonActor.prototype.draw=function(){if(!this.visible||this.points==null)return;if(this.cache){this.drawToCache();this.cache=false}var cache=this.cache_canvas;var scene=this.scene;var app=scene.app;var context=app.display.context;if(cache===null){if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;if(!this.filled&&this.stroke_style!="")context.strokeStyle=this.stroke_style;if(!this.filled)context.lineWidth=this.stroke_thickness}this.preDraw(context);var dscale=app.canvas_scale;
    var mx=app.canvas_cx+this.scene.x*dscale;var my=app.canvas_cy+this.scene.y*dscale;if(!this.ignore_camera&&(this.depth==0||this.depth==1)){mx-=scene.camera_x*dscale;my-=scene.camera_y*dscale}this.updateTransform();var trans=this.transform;var self_clip=this.self_clip;var clip_children=this.clip_children;context.setTransform(trans[0]*dscale,trans[1]*dscale,trans[2]*dscale,trans[3]*dscale,trans[4]*dscale+mx,trans[5]*dscale+my);if(self_clip)this.setClipping(context,0,0);if(cache===null)app.display.drawPolygon(0,
        0,this.points,this.filled);else context.drawImage(cache,-cache.width>>1,-cache.height>>1);this.postDraw(context);if(clip_children){if(!self_clip)this.setClipping(context,0,0)}else if(self_clip)context.restore();var count=this.actors.length;if(count>0){var acts=this.actors;for(var t=0;t<count;t++)acts[t].draw()}if(clip_children)context.restore()};
PolygonActor.prototype.drawToCache=function(){var cache=document.createElement("canvas");var w=this.w;var h=this.h;if(!this.filled&&this.stroke_style!=""){w+=this.stroke_thickness;h+=this.stroke_thickness}cache.width=w;cache.height=h;var scene=this.scene;var app=scene.app;var context=cache.getContext("2d");if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;if(!this.filled&&this.stroke_style!="")context.strokeStyle=this.stroke_style;if(!this.filled)context.lineWidth=this.stroke_thickness;
    app.display.drawPolygon(w/2,h/2,this.points,this.filled,context);this.cache_canvas=cache};RectActor.prototype=new Actor;RectActor.prototype.constructor=RectActor;RectActor.prototype.parent=Actor.prototype;function RectActor(){this.fill_style="#ffffff";this.stroke_style="#ffffff";this.stroke_thickness=1;this.corner_radius=0;this.filled=true;this.grad_rotation=0;Actor.call(this);this.type=Actor.Type_Rect}RectActor.prototype.update=function(dt){return this.baseUpdate(dt)};
RectActor.prototype.draw=function(){if(!this.visible)return;if(this.cache){this.drawToCache();this.cache=false}var cache=this.cache_canvas;var scene=this.scene;var app=scene.app;var dscale=app.canvas_scale;var context=app.display.context;if(cache===null){if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;if(!this.filled&&this.stroke_style!="")context.strokeStyle=this.stroke_style;if(!this.filled)context.lineWidth=this.stroke_thickness}this.preDraw(context);var mx=app.canvas_cx+
    scene.x*dscale;var my=app.canvas_cy+scene.y*dscale;var cx=this.w/2;var cy=this.h/2;cx=cx+.5<<0;cy=cy+.5<<0;if(!this.ignore_camera&&(this.depth==0||this.depth==1)){mx-=scene.camera_x*dscale;my-=scene.camera_y*dscale}this.updateTransform();var trans=this.transform;var self_clip=this.self_clip;var clip_children=this.clip_children;context.setTransform(trans[0]*dscale,trans[1]*dscale,trans[2]*dscale,trans[3]*dscale,trans[4]*dscale+mx,trans[5]*dscale+my);if(self_clip)this.setClipping(context,-cx,-cy);if(cache===
    null)if(this.corner_radius!=0)app.display.drawRoundRect(-cx,-cy,this.w,this.h,this.corner_radius,this.filled);else app.display.drawRect(-cx,-cy,this.w,this.h,this.filled);else context.drawImage(cache,-cache.width>>1,-cache.height>>1);this.postDraw(context);if(clip_children){if(!self_clip)this.setClipping(context,-cx,-cy)}else if(self_clip)context.restore();var count=this.actors.length;if(count>0){var acts=this.actors;for(var t=0;t<count;t++)acts[t].draw()}if(clip_children)context.restore()};
RectActor.prototype.drawToCache=function(){var cache=document.createElement("canvas");var w=this.w;var h=this.h;var ox=0;var oy=0;if(!this.filled&&this.stroke_style!=""){w+=this.stroke_thickness;h+=this.stroke_thickness;ox=this.stroke_thickness>>1;oy=this.stroke_thickness>>1}cache.width=w;cache.height=h;var scene=this.scene;var app=scene.app;var context=cache.getContext("2d");if(this.filled&&this.fill_style!="")context.fillStyle=this.fill_style;if(!this.filled&&this.stroke_style!="")context.strokeStyle=
    this.stroke_style;if(!this.filled)context.lineWidth=this.stroke_thickness;context.setTransform(1,0,0,1,w/2+ox,h/2+oy);if(this.corner_radius!=0)app.display.drawRoundRect(-w/2,-h/2,this.w,this.h,this.corner_radius,this.filled,context);else app.display.drawRect(-w/2,-h/2,this.w,this.h,this.filled,context);this.cache_canvas=cache};function Scene(){this.app=null;this.actors=[];this.removals=[];this.frame_count=0;this.world=null;this.touching=false;this.touchmove=false;this.timelines=new TimelineManager;this.layer=0;this.order_changed=true;this.name="";this.tag="";this.active=true;this.visible=true;this.x=0;this.y=0;this.w=1024;this.h=768;this.clip_children=true;this.clip_shape=null;this.camera_x=0;this.camera_y=0;this.camera_vx=0;this.camera_vy=0;this.follow_speed_x=.3;this.follow_speed_y=.3;this.target_x=null;this.target_y=
    null;this.touch_pan_x=false;this.touch_pan_y=false;this.panning=false;this.world_scale=20;this.time_step=0;this.extents=[0,0,0,0];this.opacity=1;this.bitmaps=[];this.brushes=[];this.shapes=[];this.materials=[];this.sounds=[]}Object.defineProperty(Scene.prototype,"_layer",{get:function(){return this.layer},set:function(value){if(this.layer!=value){this.layer=value;this.app.order_changed=true}}});
Scene.prototype.release=function(){if(this.onDestroy!==undefined)this.onDestroy();this.world=null;this.actors=null};Scene.prototype.destroy=function(){this.app.removeScene(this)};Scene.prototype.addActor=function(actor){this.actors.push(actor);actor.scene=this;return actor};Scene.prototype.removeActor=function(actor){this.removals.push(actor)};
Scene.prototype.removeActorsWithTag=function(tag){var acts=this.actors;var count=acts.length;var removals=this.removals;for(var t=0;t<count;t++)if(acts[t].tag==tag)removals.push(acts[t])};
Scene.prototype.cleanupDestroyedActors=function(){var dcount=this.removals.length;if(dcount>0){var removals=this.removals;var acts=this.actors;var count=acts.length;for(var s=0;s<dcount;s++){var dact=removals[s];for(var t=0;t<count;t++)if(dact==acts[t]){dact.release();acts.splice(t,1);count--;break}}}this.removals=[]};
Scene.prototype.findActor=function(name,recursive){if(recursive===undefined)recursive=false;var acts=this.actors;var count=acts.length;for(var t=0;t<count;t++)if(acts[t].name==name)return acts[t];else if(recursive){var act=acts[t].findActor(name,recursive);if(act!=null)return act}return null};Scene.prototype.bringToFront=function(){var scenes=this.app.scenes;var count=scenes.length;var i=-1;for(var t=0;t<count;t++)if(scenes[t]==this){i=t;break}if(i>=0){scenes.splice(i,1);scenes.push(this)}};
Scene.prototype.sendToBack=function(){var scenes=this.app.scenes;var count=scenes.length;var i=-1;for(var t=0;t<count;t++)if(scenes[t]==this){i=t;break}if(i>=0){scenes.splice(i,1);scenes.unshift(this)}};Scene.prototype.onKeyPressBase=function(e){if(this.onKeyPress!==undefined)this.onKeyPress(e)};Scene.prototype.onKeyDownBase=function(e){if(this.onKeyDown!==undefined)this.onKeyDown(e)};Scene.prototype.onKeyUpBase=function(e){if(this.onKeyUp!==undefined)this.onKeyUp(e)};
Scene.prototype.onBeginTouchBase=function(touch_pos){this.touching=true;if(this.onBeginTouch!==undefined)this.onBeginTouch(touch_pos)};Scene.prototype.onEndTouchBase=function(touch_pos){if(this.touching&&this.onTapped!==undefined)this.onTapped(touch_pos);this.touching=false;this.touchmove=false;if(this.onEndTouch!==undefined)this.onEndTouch(touch_pos);this.panning=false};
Scene.prototype.onMoveTouchBase=function(touch_pos){this.touchmove=true;if(this.onMoveTouch!==undefined)this.onMoveTouch(touch_pos);if(this.touching){var app=this.app;var d=0;if(this.touch_pan_x){d=app.touch_drag_x;this.camera_vx=d*app.target_frame_rate;this.camera_x+=d}if(this.touch_pan_y){d=app.touch_drag_y;this.camera_vy=d*app.target_frame_rate;this.camera_y+=d}if(d!=0)this.panning=true}};
Scene.prototype.initWorld=function(gravity_x,gravity_y,allow_sleep){if(!app.box2d)return;this.world=new Box2D.Dynamics.b2World(new Box2D.Common.Math.b2Vec2(gravity_x,gravity_y),allow_sleep);var listener=new Box2D.Dynamics.b2ContactListener;listener.BeginContact=function(contact){var actor=contact.GetFixtureA().GetBody().GetUserData();if(actor.onCollisionStart!==undefined)actor.onCollisionStart(contact);actor=contact.GetFixtureB().GetBody().GetUserData();if(actor.onCollisionStart!==undefined)actor.onCollisionStart(contact)};
    listener.EndContact=function(contact){var actor=contact.GetFixtureA().GetBody().GetUserData();if(actor.onCollisionEnd!==undefined)actor.onCollisionEnd(contact);actor=contact.GetFixtureB().GetBody().GetUserData();if(actor.onCollisionEnd!==undefined)actor.onCollisionEnd(contact)};this.world.SetContactListener(listener)};
Scene.prototype.draw=function(){if(!this.visible)return;var app=this.app;var dscale=app.canvas_scale;var context=app.display.context;if(this.clip_children){var x=app.canvas_cx+this.x;var y=app.canvas_cy+this.y;context.setTransform(dscale,0,0,dscale,x,y);context.save();context.beginPath();if(this.clip_shape==null)context.rect(-this.w/2,-this.h/2,this.w,this.h);else{var shape=this.clip_shape;if(this.clip_shape.type==Shape.TypeBox)context.rect(0,0,shape.width,shape.height);else if(this.clip_shape.type==
    Shape.TypeCircle)context.arc(0,0,shape.width,0,2*Math.PI,false);else if(this.clip_shape.type==Shape.TypePolygon){var points=shape.vertices;var count=points.length;context.moveTo(points[0],points[1]);for(var i=2;i<count;i+=2)context.lineTo(points[i],points[i+1]);context.closePath()}}context.clip()}var acts=this.actors;var count=acts.length;for(var t=0;t<count;t++)acts[t].draw();if(this.clip_children)context.restore()};
Scene.prototype.baseUpdate=function(dt){if(!this.active)return false;if(this.onTick!==undefined)this.onTick(dt);this.timelines.update(dt);this.updateCamera(dt);if(this.world!=null){var app=window.app;if(this.time_step==0)this.world.Step(dt,10,10);else{var run_count=1;if(app.adaptive_physics){run_count=app.target_frame_rate/app.avg_fps+.5<<0;if(run_count<1)run_count=1;else if(run_count>3)run_count=3}for(var t=0;t<run_count;t++)this.world.Step(this.time_step,10,10)}}var acts=this.actors;var count=acts.length;
    for(var t=0;t<count;t++)acts[t].update(dt);if(this.world!=null)this.world.ClearForces();this.frame_count++;this.cleanupDestroyedActors();if(this.order_changed){this.order_changed=false;Utils.sortLayers(this.actors)}return true};Scene.prototype.update=function(dt){return this.baseUpdate(dt)};
Scene.prototype.updateCamera=function(dt){if(this.target_x!=null)if(this.follow_speed_x==0){this.camera_x=this.target_x.x;this.camera_vx=0}else this.camera_vx+=(this.target_x.x-this.camera_x)*this.follow_speed_x;if(this.target_y!=null)if(this.follow_speed_y==0){this.camera_y=this.target_y.y;this.camera_vy=0}else this.camera_vy+=(this.target_y.y-this.camera_y)*this.follow_speed_y;if(!this.touching){this.camera_x+=this.camera_vx*dt;this.camera_y+=this.camera_vy*dt;this.camera_vx*=.9;this.camera_vy*=
    .9}if(this.camera_x!=0||this.camera_y!=0){var ew=this.extents[2];var eh=this.extents[3];var sw=this.app.canvas_width;var sh=this.app.canvas_height;if(ew!=0&&sw<=ew){var cx=sw/2;var left=this.extents[0]+cx;var right=this.extents[0]+ew-cx;if(this.camera_x<left){this.camera_x=left;this.camera_vx=0}if(this.camera_x>right){this.camera_x=right;this.camera_vx=0}}if(sw>ew)this.camera_x=0;if(eh!=0&&sh<=eh){var cy=sh/2;var top=this.extents[1]+cy;var bottom=this.extents[1]+eh-cy;if(this.camera_y<top){this.camera_y=
    top;this.camera_vy=0}if(this.camera_y>bottom){this.camera_y=bottom;this.camera_vy=0}}if(sh>eh)this.camera_y=0}};Scene.prototype.findHitActor=function(position){var acts=this.actors;var count=acts.length;var hit=null;for(var t=count-1;t>=0;t--){hit=acts[t].hitTest(position);if(hit!=null)return hit}return hit};Scene.prototype.dirty=function(){var a=this.actors;var count=a.length;for(var t=0;t<count;t++)a[t].dirty()};
Scene.prototype.getResFromType=function(type){if(type=="brush")return this.brushes;else if(type=="sound")return this.sounds;else if(type=="shape")return this.shapes;else if(type=="material")return this.materials;else if(type=="bitmap")return this.bitmaps;return null};Scene.prototype.addResource=function(resource,type){var res=this.getResFromType(type);if(res!=null){res.push(resource);res.parent=this}};
Scene.prototype.removeResource=function(resource,type){var res=this.getResFromType(type);if(res!=null){var count=res.length;for(var t=0;t<count;t++)if(res[t].name==name){res.parent=null;res.splice(t,1);return}}};Scene.prototype.findResource=function(name,type){var res=this.getResFromType(type);if(res==null)return null;var count=res.length;for(var t=0;t<count;t++)if(res[t].name==name)return res[t];return this.app.findResource(name,type)};
Scene.prototype.areResourcesLoaded=function(){var res=this.bitmaps;var count=res.length;for(var t=0;t<count;t++)if(!res[t].loaded)return false;return true};function Shape(name){this.parent=null;this.name=name;this.type=Shape.TypeBox;this.width=0;this.height=0;this.vertices=[];this.convexVertices=[]}Shape.TypeBox=0;Shape.TypeCircle=1;Shape.TypePolygon=2;Shape.prototype.typeToConst=function(type_name){if(shape.type=="polygon")return Shape.TypePolygon;else if(shape.type=="circle")return Shape.TypeCircle;return Shape.TypeBox};Shape.prototype.remove=function(){if(this.parent!=null)this.parent.removeResource(this,"shape")};function Sound(name,location,reuse){this.parent=null;this.name=name;this.location=location;if(reuse!==undefined)this.reuse=reuse;else this.reuse=false;this.snd=null}Sound.prototype.play=function(){var snd;if(this.reuse)snd=this.snd;if(snd==null)if(window.app.use_marm)snd=new Media("/android_asset/webassets/"+this.location);else snd=new Audio(this.location);snd.play();this.snd=snd;return snd};Sound.prototype.stop=function(){if(this.reuse&&this.snd!=null)this.snd.stop()};
Sound.prototype.pause=function(){if(this.reuse&&this.snd!=null)this.snd.pause()};Sound.prototype.destroy=function(){if(this.parent!=null)if(window.app.use_marm){if(window.app.use_marm&&this.snd!=null)this.snd.release();this.parent.removeResource(this,"sound")}};function Utils(){}Utils.sortLayers=function(objs){var cnt=objs.length;var s,t;for(t=0;t<cnt;t++)for(s=t+1;s<cnt;s++)if(objs[t].layer>objs[s].layer){var obj=objs[t];objs[t]=objs[s];objs[s]=obj}};function Xoml(app){this.current_scene=null;this.app=app}Xoml.loadJSON=function(filename,blocking,callback){var req=new XMLHttpRequest;req.open("GET",filename,!blocking);if(!blocking)req.onreadystatechange=function(){if(req.readyState==4&&req.status==200)callback(req.responseText);else callback(null)};req.send();if(blocking)if(req.status==200)callback(req.responseText);else callback(null)};
Xoml.loadJS=function(filename){var fileref=document.createElement("script");fileref.setAttribute("type","text/javascript");fileref.setAttribute("src",filename);if(typeof fileref!="undefined")document.getElementsByTagName("head")[0].appendChild(fileref)};
Xoml.prototype.parseScene=function(parent,item){if(this.app.debug)console.log("Parsing Scene "+item.Name);var scene=new Scene;this.current_scene=scene;scene.name=item.Name;if(item.Tag!==undefined)scene.tag=item.Tag;scene.x=item.Position.x;scene.y=item.Position.y;if(item.CanvasSize!==undefined){scene.w=item.CanvasSize.x;scene.h=item.CanvasSize.y}if(item.Layer!==undefined)scene.layer=item.Layer;if(item.Visible!==undefined)scene.visible=item.Visible;if(item.Active!==undefined)scene.active=item.Active;
    if(item.Physics!==undefined&&item.Physics){scene.initWorld(item.Gravity.x,item.Gravity.y,item.DoSleep);if(item.PhysicsTimestep!==undefined)scene.time_step=item.PhysicsTimestep;if(item.WorldScale!==undefined)scene.world_scale=item.WorldScale}if(item.ClipChildren!==undefined)scene.clip_children=item.ClipChildren;if(item.TouchPan=="Both"){scene.touch_pan_x=true;scene.touch_pan_y=true}else if(item.TouchPan=="X")scene.touch_pan_x=true;else if(item.TouchPan=="Y")scene.touch_pan_y=true;scene.extents[0]=
        item.Extents.x;scene.extents[1]=item.Extents.y;scene.extents[2]=item.Extents.w;scene.extents[3]=item.Extents.h;scene.follow_speedx=item.FollowSpeed.x;scene.follow_speedy=item.FollowSpeed.y;parent.addScene(scene);if(item.Current)parent.focus_scene=scene;var user_props=item.UserProps;if(user_props!==undefined)for(var t=0;t<user_props.length;t++)scene[user_props[t].Name]=user_props[t].Value;if(item.Alpha!==undefined)scene.opacity=item.Alpha;if(!(item.Children===undefined))this.parseResources(scene,item.Children);
    if(item.ClipShape!==undefined&&item.ClipShape!="")scene.clip_shape=scene.findResource(item.ClipShape,"shape");if(item.TargetX!="")scene.target_x=scene.findActor(item.TargetX);if(item.TargetY!="")scene.target_y=scene.findActor(item.TargetY);if(item.OnCreate!==undefined)scene.onCreate=function(){eval(item.OnCreate)};if(item.OnDestroy!==undefined)scene.onDestroy=function(){eval(item.OnDestroy)};if(item.OnTick!==undefined)scene.onTick=function(dt){eval(item.OnTick)};if(item.OnTapped!==undefined)scene.onTapped=
        function(touch_pos){eval(item.OnTapped)};if(item.OnBeginTouch!==undefined)scene.onBeginTouch=function(touch_pos){eval(item.OnBeginTouch)};if(item.OnEndTouch!==undefined)scene.onEndTouch=function(touch_pos){eval(item.OnEndTouch)};if(item.OnMoveTouch!==undefined)scene.onMoveTouch=function(touch_pos){eval(item.OnMoveTouch)};if(item.OnKeyPress!==undefined)scene.onKeyPress=function(e){eval(item.OnKeyPress)};if(item.OnKeyDown!==undefined)scene.onKeyDown=function(e){eval(item.OnKeyDown)};if(item.OnKeyUp!==
        undefined)scene.onKeyUp=function(e){eval(item.OnKeyUp)};if(scene.onCreate!==undefined)scene.onCreate()};
Xoml.prototype.parseBrush=function(parent,item){if(this.app.debug)console.log("Parsing Brush "+item.Name);var brush;if(item.BrushType==0){var rect=item.Rect;var bitmap=parent.findResource(item.Image,"bitmap");var frames=item.Frames;if(frames.length==0)brush=new ImageAtlas(item.Name,bitmap,rect.x,rect.y,rect.w,rect.h);else{brush=new ImageAtlas(item.Name,bitmap);for(var t=0;t<frames.length;t++){var frame=frames[t];brush.addFrame(frame.x,frame.y,frame.w,frame.h)}}}else{var stops=item.Stops;brush=new Gradient(item.Name);
    for(var t=0;t<stops.length;t++){var stop=stops[t];brush.addColourStop(stop.c,stop.o)}if(item.Angle!==undefined)brush.angle=item.Angle}parent.addResource(brush,"brush")};Xoml.prototype.parseImage=function(parent,item){if(this.app.debug)console.log("Parsing Image "+item.Name);var bitmap=new Bitmap(item.Name,item.Location,item.Preload);parent.addResource(bitmap,"bitmap")};
Xoml.prototype.parseSound=function(parent,item){if(this.app.debug)console.log("Parsing Sound "+item.Name);var sound=new Sound(item.Name,item.Location,item.Reuse);parent.addResource(sound,"sound")};Xoml.prototype.parseFont=function(parent,item){if(this.app.debug)console.log("Parsing Font "+item.Name)};
Xoml.prototype.parseShape=function(parent,item){if(this.app.debug)console.log("Parsing Shape "+item.Name);var shape=new Shape(item.Name);shape.width=item.Width;shape.height=item.Height;if(item.ShapeType=="Circle")shape.type=Shape.TypeCircle;else if(item.ShapeType=="Box")shape.type=Shape.TypeBox;else if(item.ShapeType=="Polygon"){shape.type=Shape.TypePolygon;var vertices=item.Vertices;var count=vertices.length;for(var t=0;t<count;t++)shape.vertices.push(vertices[t]);if(item.ConvexVertices!==undefined){var pc=
    item.ConvexVertices.length;for(var t=0;t<pc;t++){var ov=[];var vertices=item.ConvexVertices[t];count=vertices.length;for(var s=0;s<count;s++)ov.push(vertices[s]);shape.convexVertices.push(ov)}}}parent.addResource(shape,"shape")};
Xoml.prototype.parseMaterial=function(parent,item){if(this.app.debug)console.log("Parsing Material "+item.Name);var material=new Material;material.name=item.Name;material.type=item.MaterialType;material.density=item.Density;material.friction=item.Friction;material.restitution=item.Restitution;material.gravity_scale=item.GravityScale;material.fixed_rotation=item.FixedRotation;material.is_bullet=item.IsBullet;parent.addResource(material,"material")};
Xoml.prototype.parseActor=function(actor,parent,item){if(this.app.debug)console.log("Parsing Actor "+item.Name);var brush=null;actor.scene=this.current_scene;if(item.Name!==undefined)actor.name=item.Name;if(item.Tag!==undefined)actor.tag=item.Tag;if(item.Visible!==undefined)actor.visible=item.Visible;if(item.Active!==undefined)actor.active=item.Active;if(item.Layer!==undefined)actor.layer=item.Layer;if(item.Position!==undefined){actor.x=item.Position.x;actor.y=item.Position.y}if(item.Scale!==undefined){actor.scale_x=
    item.Scale.x;actor.scale_y=item.Scale.y}if(item.FlipX!==undefined&&item.FlipX)actor.scale_x=-actor.scale_x;if(item.FlipY!==undefined&&item.FlipY)actor.scale_y=-actor.scale_y;if(item.Angle!==undefined)actor.rotation=item.Angle;if(item.StrokeColour!==undefined)actor.stroke_style=item.StrokeColour;if(item.Filled!==undefined)actor.filled=item.Filled;if(item.Thickness!==undefined)actor.stroke_thickness=item.Thickness;if(item.Size!==undefined){actor.w=item.Size.x;actor.h=item.Size.y}if(item.Origin!==undefined){actor.ox=
    item.Origin.x;actor.oy=item.Origin.y}if(actor.ox<=-1||actor.ox>=1||actor.oy<=-1||actor.oy>=1)actor.absolute_origin=true;if(item.Alpha!==undefined)actor.opacity=item.Alpha;if(item.UseParentOpacity!==undefined)actor.use_parent_opacity=item.UseParentOpacity;if(item.Depth!==undefined)actor.depth=item.Depth;actor.use_transform=true;if(item.Velocity!==undefined){actor.vx=item.Velocity.x;actor.vy=item.Velocity.y}if(item.AngularVelocity!==undefined)actor.vr=item.AngularVelocity;if(item.VelocityDamping!==
    undefined){actor.vx_damping=item.VelocityDamping.x;actor.vy_damping=item.VelocityDamping.y}if(item.AngularVelocityDamping!==undefined)actor.vr_damping=item.AngularVelocityDamping;if(item.WrapPosition!==undefined)actor.wrap_position=item.WrapPosition;if(item.IgnoreCamera!==undefined)actor.ignore_camera=item.IgnoreCamera;if(item.ClipChildren!==undefined)actor.clip_children=item.ClipChildren;if(item.Touchable!==undefined)actor.touchable=item.Touchable;if(item.Bubbling!==undefined)actor.bubbling=item.Bubbling;
    if(item.Docking!==undefined){var docking=item.Docking;if(docking=="top"||docking=="topleft"||docking=="topright")actor.dock_y=Actor.Dock_Top;else if(docking=="bottom"||docking=="bottomleft"||docking=="bottomright")actor.dock_y=Actor.Dock_Bottom;if(docking=="left"||docking=="topleft"||docking=="bottomleft")actor.dock_x=Actor.Dock_Left;else if(docking=="right"||docking=="topright"||docking=="bottomright")actor.dock_x=Actor.Dock_Right}if(item.Margin!==undefined){actor.margin[0]=item.Margin.x;actor.margin[1]=
        item.Margin.y;actor.margin[2]=item.Margin.w;actor.margin[3]=item.Margin.h}if(item.ClipMargin!==undefined){actor.clip_margin[0]=item.ClipMargin.x;actor.clip_margin[1]=item.ClipMargin.y;actor.clip_margin[2]=item.ClipMargin.w;actor.clip_margin[3]=item.ClipMargin.h}if(item.Shadow!==undefined)actor.shadow=item.Shadow;if(item.ShadowOffset!==undefined){actor.shadow_x=item.ShadowOffset.x;actor.shadow_y=item.ShadowOffset.y}if(item.ShadowBlur!==undefined)actor.shadow_blur=item.ShadowBlur;if(item.ShadowColour!==
        undefined)actor.shadow_colour=item.ShadowColour;if(item.CompositeOp!==undefined)actor.composite_op=item.CompositeOp;if(item.Frames!==undefined&&item.Frames.length>0){var frames=item.Frames;var count=frames.length;actor.anim_frames=[];for(var t=0;t<count;t++)actor.anim_frames.push(frames[t])}if(item.AnimSpeed!==undefined)actor.frame_speed=item.AnimSpeed;if(item.Background!==undefined){brush=this.current_scene.findResource(item.Background,"brush");if(brush.stops!==undefined){var grad=brush.createStyle(actor.w,
        actor.h,item.GStart,item.GEnd);if(actor.filled)actor.fill_style=grad;else actor.stroke_style=grad}else actor.atlas=brush}parent.addActor(actor);if(item.OnCreate!==undefined)actor.onCreate=function(){eval(item.OnCreate)};if(item.OnDestroy!==undefined)actor.onDestroy=function(){eval(item.OnDestroy)};if(item.OnTick!==undefined)actor.onTick=function(dt){eval(item.OnTick)};if(item.OnTapped!==undefined){actor.touchable=true;actor.onTapped=function(touch_pos){eval(item.OnTapped)}}if(item.OnBeginTouch!==
        undefined){actor.touchable=true;actor.onBeginTouch=function(touch_pos){eval(item.OnBeginTouch)}}if(item.OnEndTouch!==undefined){actor.touchable=true;actor.onEndTouch=function(touch_pos){eval(item.OnEndTouch)}}if(item.OnMoveTouch!==undefined){actor.touchable=true;actor.onMoveTouch=function(touch_pos){eval(item.OnMoveTouch)}}if(item.OnLostTouchFocus!==undefined){actor.touchable=true;actor.onLostTouchFocus=function(touch_pos){eval(item.OnLostTouchFocus)}}if(item.OnCollisionStart!==undefined)actor.onCollisionStart=
        function(contact){eval(item.OnCollisionStart)};if(item.OnCollisionEnd!==undefined)actor.onCollisionEnd=function(contact){eval(item.OnCollisionEnd)};var user_props=item.UserProps;if(user_props!==undefined)for(var t=0;t<user_props.length;t++)actor[user_props[t].Name]=user_props[t].Value;var fixtures=item.Fixtures;if(fixtures!==undefined)for(var t=0;t<fixtures.length;t++){var options={};var material=null;var shape=null;if(fixtures[t].Material!==undefined&&fixtures[t].Material!="")material=this.current_scene.findResource(fixtures[t].Material,
        "material");if(fixtures[t].Shape!==undefined&&fixtures[t].Shape!="")shape=this.current_scene.findResource(fixtures[t].Shape,"shape");if(t==0)actor.initBody(material.type,material.fixed_rotation,material.is_bullet);if(shape==null)if(item.RenderAs==1){options.type=Shape.TypeCircle;options.radius=actor.w/2*actor.scale_x}else{options.type=Shape.TypeBox;options.width=actor.w*actor.scale_x;options.height=actor.h*actor.scale_y}else{if(shape.type==Shape.TypePolygon)if(shape.convexVertices.length>0){options.convexPoints=
        [];for(var s=0;s<shape.convexVertices.length;s++){var points=[];var v=shape.convexVertices[s];for(var i=0;i<v.length;i+=2){points.push(v[i]*actor.scale_x);points.push(v[i+1]*actor.scale_y)}options.convexPoints.push(points)}}else{options.points=[];for(var i=0;i<shape.vertices.length;i+=2){options.points.push(shape.vertices[i]*actor.scale_x);options.points.push(shape.vertices[i+1]*actor.scale_y)}}else if(shape.type==Shape.TypeCircle)options.radius=shape.width*actor.scale_x;else{options.width=shape.width*
        actor.scale_x;options.height=shape.height*actor.scale_y}options.type=shape.type}if(material!=null){options.density=material.density;options.friction=material.friction;options.restitution=material.restitution}options.is_sensor=fixtures[t].Sensor;actor.addFixture(options)}var joints=item.Joints;if(joints!==undefined)for(var t=0;t<joints.length;t++){var options=[];var actor_b=this.current_scene.findActor(joints[t].ActorB);options.type=joints[t].Type;options.actor_b=actor_b;options.anchor_a=joints[t].OffsetA;
        options.anchor_b=joints[t].OffsetB;options.self_collide=joints[t].SelfCollide;options.damping=joints[t].Damping;options.frequency=joints[t].Frequency;options.limit_joint=joints[t].LimitJoint;options.lower_limit=joints[t].LowerLimit;options.upper_limit=joints[t].UpperLimit;options.motor_enabled=joints[t].MotorEnabled;options.motor_speed=joints[t].MotorSpeed;options.max_motor_torque=joints[t].MaxMotorTorque;options.max_motor_force=joints[t].MaxMotorForce;options.ground_a=joints[t].GroundA;options.ground_b=
            joints[t].GroundB;options.axis=joints[t].Axis;options.ratio=joints[t].Ratio;actor.addJoint(options)}if(actor.body!=null){var b2Vec2=Box2D.Common.Math.b2Vec2;actor.body.SetLinearVelocity(new b2Vec2(actor.vx,actor.vy));actor.body.SetAngularVelocity(actor.vr);actor.body.SetLinearDamping(actor.vx_damping);actor.body.SetAngularDamping(actor.vr_damping)}if(item.Children!==undefined)this.parseResources(actor,item.Children)};
Xoml.prototype.parseIcon=function(parent,item){if(this.app.debug)console.log("Parsing Icon "+item.Name);var actor;var render_as=0;if(item.RenderAs!==undefined)render_as=item.RenderAs;if(render_as==1)actor=new ArcActor;else if(render_as==2)actor=new RectActor;else if(render_as==0)if(item.Geometry!==undefined){actor=new PolygonActor;var shape=this.current_scene.findResource(item.Geometry,"shape");if(shape!=null)actor.points=shape.vertices}else actor=new Actor;if(item.Colour!==undefined)actor.fill_style=
    item.Colour;if(item.CornerRadius!==undefined)actor.corner_radius=item.CornerRadius;this.parseActor(actor,parent,item);if(render_as==1)actor.radius=actor.w/2;if(item.Virtual!==undefined&&item.Virtual){actor.makeVirtual();if(item.ScrollRange!==undefined){actor.scroll_range[0]=item.ScrollRange.x;actor.scroll_range[1]=item.ScrollRange.y;actor.scroll_range[2]=item.ScrollRange.w;actor.scroll_range[3]=item.ScrollRange.h}if(item.ScrollPos!==undefined){actor.scroll_pos_x=item.ScrollPos.x;actor.scroll_pos_y=
    item.ScrollPos.y}}if(item.SelfClip!==undefined)actor.self_clip=item.SelfClip;if(item.ClipShape!==undefined)actor.clip_shape=this.current_scene.findResource(item.ClipShape,"shape");if(item.Cache==true)actor.cache=true;if(actor.onCreate!==undefined)actor.onCreate()};
Xoml.prototype.parseLabel=function(parent,item){if(this.app.debug)console.log("Parsing Label "+item.Name);var actor=new LabelActor;actor.text=item.Text;actor.font=item.Font;actor.text_align=item.AlignH;actor.text_baseline=item.AlignV;if(item.TextColour!==undefined)actor.fill_style=item.TextColour;this.parseActor(actor,parent,item);if(item.Cache==true)actor.drawToCache();if(actor.onCreate!==undefined)actor.onCreate()};
Xoml.prototype.parseResources=function(parent,objects){var count=objects.length;for(var t=0;t<count;t++){var res_type=objects[t].ResourceType;if(res_type=="Scene")this.parseScene(parent,objects[t]);else if(res_type=="Brush")this.parseBrush(parent,objects[t]);else if(res_type=="Image")this.parseImage(parent,objects[t]);else if(res_type=="Sound")this.parseSound(parent,objects[t]);else if(res_type=="Font")this.parseFont(parent,objects[t]);else if(res_type=="Shape")this.parseShape(parent,objects[t]);
else if(res_type=="Material")this.parseMaterial(parent,objects[t]);else if(res_type=="Icon")this.parseIcon(parent,objects[t]);else if(res_type=="Label")this.parseLabel(parent,objects[t])}};